//! Wire-format trait and its two implementations.
//!
//! [`WireFormat`] is a serialize/deserialize contract for protocol wire types.
//! Two implementations:
//!
//! - [`Uncompressed`] (tag `0x00`): verbatim little-endian concatenation. Fully
//!   implemented; the baseline for KAT byte-parity.
//! - [`PrgCompressed`] (tag `0x01`): RLWE mask polynomials are replaced by a
//!   32-byte seed (regenerated by `Shake256Prg`); the body is stored verbatim.
//!   **Mask regeneration is fully implemented** (the parity-critical part);
//!   `serialize` remains a sanctioned `todo!()` (the mask/body disambiguation
//!   happens at the `MLWECiphertext` level in P5).
//!
//! # Tag byte (first byte of every packet)
//!
//! | Tag  | Format        |
//! |------|---------------|
//! | 0x00 | Uncompressed  |
//! | 0x01 | PrgCompressed |
//!
//! # PrgCompressed mask-regeneration contract (pinned for the P5 cross-language KAT)
//!
//! Seed → `Shake256Prg::new(seed)`, then for each coefficient position in
//! row-major mask order (`masks[0][0..N], masks[1][0..N], …`) draw
//! `prg.uniform_below(q)` (for RNS, one draw per limb, limb-0 first). This is
//! byte-identical to the Python reference's `randbelow(q)` order.

use alloc::vec::Vec;

use via_primitives::sampling::Shake256Prg;

use crate::error::{Result, ViaError};

// ---------------------------------------------------------------------------
// WireFormat trait
// ---------------------------------------------------------------------------

/// Serialize / deserialize contract for VIA-C wire types. `T` is the wire type.
/// The format tag byte is emitted by `serialize` and validated by `deserialize`.
pub trait WireFormat<T> {
    /// Serialize `value` into a byte vector.
    ///
    /// # Errors
    ///
    /// Returns `Err(ViaError::DimMismatch(..))` if `value`'s internal dims are
    /// inconsistent.
    fn serialize(value: &T) -> Result<Vec<u8>>;

    /// Deserialize a `T` from the byte slice `buf`.
    ///
    /// # Errors
    ///
    /// - `ViaError::BufferTooShort` if `buf` is shorter than required.
    /// - `ViaError::UnknownFormatTag(tag)` if the leading tag does not match.
    /// - `ViaError::InvalidPrgSeed` for malformed PRG seeds (`PrgCompressed`).
    fn deserialize(buf: &[u8]) -> Result<T>;
}

/// Encode `u64` coefficients as little-endian bytes (8 bytes each).
fn encode_coeffs_u64(coeffs: &[u64], out: &mut Vec<u8>) {
    for &c in coeffs {
        out.extend_from_slice(&c.to_le_bytes());
    }
}

/// Decode `count` little-endian `u64` coefficients from `buf[offset..]`,
/// returning the values and the new offset.
///
/// # Errors
///
/// `ViaError::BufferTooShort` if fewer than `count * 8` bytes remain.
fn decode_coeffs_u64(buf: &[u8], offset: usize, count: usize) -> Result<(Vec<u64>, usize)> {
    let end = offset + count * 8;
    if buf.len() < end {
        return Err(ViaError::BufferTooShort {
            needed: end,
            got: buf.len(),
        });
    }
    let mut out = Vec::with_capacity(count);
    for i in 0..count {
        let b = &buf[offset + i * 8..offset + i * 8 + 8];
        out.push(u64::from_le_bytes(b.try_into().unwrap()));
    }
    Ok((out, end))
}

// ---------------------------------------------------------------------------
// Uncompressed — verbatim byte concatenation
// ---------------------------------------------------------------------------

/// Marker type for the verbatim uncompressed wire format (tag `0x00`).
pub struct Uncompressed;

impl Uncompressed {
    const TAG: u8 = 0x00;
}

/// Uncompressed round-trip for a flat `Vec<u64>` — the canonical codec for one
/// polynomial's coefficient vector. P5 plugs the full `MLWECiphertext` impls in
/// on top of this byte layout.
///
/// ```text
/// [tag: 0x00] [count: 8 bytes LE u64] [coeff_0: 8 bytes LE] … [coeff_{n-1}]
/// ```
impl WireFormat<Vec<u64>> for Uncompressed {
    fn serialize(value: &Vec<u64>) -> Result<Vec<u8>> {
        let mut out = Vec::with_capacity(1 + 8 + value.len() * 8);
        out.push(Self::TAG);
        out.extend_from_slice(&(value.len() as u64).to_le_bytes());
        encode_coeffs_u64(value, &mut out);
        Ok(out)
    }

    fn deserialize(buf: &[u8]) -> Result<Vec<u64>> {
        if buf.is_empty() {
            return Err(ViaError::BufferTooShort { needed: 1, got: 0 });
        }
        if buf[0] != Self::TAG {
            return Err(ViaError::UnknownFormatTag(buf[0]));
        }
        if buf.len() < 9 {
            return Err(ViaError::BufferTooShort {
                needed: 9,
                got: buf.len(),
            });
        }
        let count = u64::from_le_bytes(buf[1..9].try_into().unwrap()) as usize;
        let (coeffs, _) = decode_coeffs_u64(buf, 9, count)?;
        Ok(coeffs)
    }
}

// ---------------------------------------------------------------------------
// PrgCompressed — mask-regeneration implemented; serialize is todo!()
// ---------------------------------------------------------------------------

/// PRG-seed-compressed wire format (tag `0x01`). On the wire:
/// `[tag=0x01] [seed: SEED_LEN bytes] [count: 8 bytes LE] [body coeffs verbatim]`.
/// Masks are regenerated by `Shake256Prg(seed)` rather than transmitted.
pub struct PrgCompressed<const SEED_LEN: usize = 32>;

impl<const SEED_LEN: usize> PrgCompressed<SEED_LEN> {
    const TAG: u8 = 0x01;

    /// Regenerate `count` mask coefficients from a PRG seed at modulus `q`.
    ///
    /// The **only** fully-implemented `PrgCompressed` method. The PRG is seeded
    /// with the verbatim seed bytes; draws are `uniform_below(q)` in row-major
    /// mask order (`masks[0][0], masks[0][1], …, masks[RANK-1][N-1]`; for RNS,
    /// one draw per limb, limb-0 first). This order is byte-identical to the
    /// Python reference and pinned for the P5 cross-language KAT.
    ///
    /// # Panics
    ///
    /// Panics if `seed.len() > 64` (the `Shake256Prg` seed cap).
    pub fn regenerate_masks(seed: &[u8], q: u64, count: usize) -> Vec<u64> {
        let mut prg = Shake256Prg::new(seed);
        (0..count).map(|_| prg.uniform_below(q)).collect()
    }
}

/// `PrgCompressed` `WireFormat<Vec<u64>>`: deserialize (body verbatim) is
/// implemented; `serialize` is a sanctioned `todo!()` (mask/body
/// disambiguation lands at the `MLWECiphertext` level in P5).
impl<const SEED_LEN: usize> WireFormat<Vec<u64>> for PrgCompressed<SEED_LEN> {
    fn serialize(_value: &Vec<u64>) -> Result<Vec<u8>> {
        todo!(
            "PrgCompressed::serialize — implemented in P5 integration; \
             only mask-regen is implemented at this layer"
        )
    }

    fn deserialize(buf: &[u8]) -> Result<Vec<u64>> {
        if buf.is_empty() {
            return Err(ViaError::BufferTooShort { needed: 1, got: 0 });
        }
        if buf[0] != Self::TAG {
            return Err(ViaError::UnknownFormatTag(buf[0]));
        }
        let header_len = 1 + SEED_LEN + 8;
        if buf.len() < header_len {
            return Err(ViaError::BufferTooShort {
                needed: header_len,
                got: buf.len(),
            });
        }
        let count =
            u64::from_le_bytes(buf[1 + SEED_LEN..1 + SEED_LEN + 8].try_into().unwrap()) as usize;
        let (body_coeffs, _) = decode_coeffs_u64(buf, header_len, count)?;
        Ok(body_coeffs)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn uncompressed_vec_round_trip_empty() {
        let orig: Vec<u64> = Vec::new();
        let bytes = Uncompressed::serialize(&orig).unwrap();
        let decoded = Uncompressed::deserialize(&bytes).unwrap();
        assert_eq!(orig, decoded);
    }

    #[test]
    fn uncompressed_vec_round_trip_small() {
        let orig: Vec<u64> = alloc::vec![0, 1, 137_438_822_401, u64::MAX];
        let bytes = Uncompressed::serialize(&orig).unwrap();
        assert_eq!(bytes[0], Uncompressed::TAG);
        let decoded = Uncompressed::deserialize(&bytes).unwrap();
        assert_eq!(orig, decoded);
    }

    #[test]
    fn uncompressed_wrong_tag_returns_error() {
        let mut bytes = Uncompressed::serialize(&alloc::vec![1u64, 2]).unwrap();
        bytes[0] = 0xFF; // corrupt tag
        let err = Uncompressed::deserialize(&bytes).unwrap_err();
        assert_eq!(err, ViaError::UnknownFormatTag(0xFF));
    }

    #[test]
    fn uncompressed_buffer_too_short_returns_error() {
        let err = Uncompressed::deserialize(&[]).unwrap_err();
        assert_eq!(err, ViaError::BufferTooShort { needed: 1, got: 0 });
    }

    /// The cross-language KAT contract: `regenerate_masks(seed, q, N)` must
    /// equal `[Shake256Prg::new(seed).uniform_below(q) for _ in 0..N]` (which in
    /// turn matches Python `DeterministicSampler(seed).randbelow(q)`).
    #[test]
    fn prg_mask_regen_matches_shake256prg_draw() {
        let q: u64 = 8_380_417; // VIA-C q3
        let seed = b"mask-seed";
        let regen = PrgCompressed::<32>::regenerate_masks(seed, q, 4);
        let mut prg = Shake256Prg::new(seed);
        let expected: Vec<u64> = (0..4).map(|_| prg.uniform_below(q)).collect();
        assert_eq!(
            regen, expected,
            "mask-regen must match direct Shake256Prg draw"
        );
    }

    #[test]
    fn prg_mask_regen_respects_modulus_bound() {
        let q: u64 = 8_380_417;
        let masks = PrgCompressed::<32>::regenerate_masks(b"range-check", q, 200);
        for m in &masks {
            assert!(*m < q, "mask coefficient {m} out of range [0, {q})");
        }
    }

    #[test]
    fn prg_compressed_deserialize_body_only() {
        let seed = [0u8; 32];
        let body: Vec<u64> = alloc::vec![42u64, 99u64];
        let mut buf = alloc::vec![PrgCompressed::<32>::TAG];
        buf.extend_from_slice(&seed);
        buf.extend_from_slice(&(body.len() as u64).to_le_bytes());
        for b in &body {
            buf.extend_from_slice(&b.to_le_bytes());
        }
        let decoded = PrgCompressed::<32>::deserialize(&buf).unwrap();
        assert_eq!(decoded, body);
    }

    #[test]
    fn prg_compressed_wrong_tag_returns_error() {
        let mut buf = alloc::vec![0xFF_u8; 50];
        buf[0] = 0x00; // wrong tag for PrgCompressed
        let err = PrgCompressed::<32>::deserialize(&buf).unwrap_err();
        assert_eq!(err, ViaError::UnknownFormatTag(0x00));
    }
}
