//! Key-bundle wire types: [`QueryCompressionKey`] and [`PublicParams`].

use alloc::boxed::Box;
use core::fmt;

use via_primitives::algebra::ring::RingPoly;
use via_primitives::encryption::types::RLevCiphertext;
use via_primitives::switching::RingSwitchKey;
use zeroize::{Zeroize, ZeroizeOnDrop};

use crate::params::PIRParams;
use crate::presets::{ViaCPublicParams, pir_params_matches_preset};

// ---------------------------------------------------------------------------
// QueryCompressionKey<K>
// ---------------------------------------------------------------------------

/// Key material for server-side query decompression — `pp_qck` in the paper
/// (Appendix C.1: `pp_qck = (ĉ_toRLWE, ĉ_toRGSW)`, both in `R^{ℓ_conv}_{n1,q1}`).
///
/// Bundles the LWE→RLWE cascade key (type `K`, supplied by the P2 cascade
/// instantiation — `ĉ_toRLWE`) and the RLWE→RGSW conversion key
/// $\mathrm{RLev}_{S_1}(S_1^2)$ at depth `L_CK` (`ĉ_toRGSW`, generated by
/// `gen_rlwe_to_rgsw_key`).
///
/// The cascade key is large (~24.75 MB at realistic depth 18) and lives on the
/// heap (`Box<K>`); both fields are derived from $S_1$ and are as sensitive as
/// the secret key, so this type is [`ZeroizeOnDrop`] with a redacting `Debug`.
pub struct QueryCompressionKey<K: Zeroize, const N1: usize, R1: RingPoly<N1>, const L_CK: usize> {
    /// LWE→RLWE conversion (cascade) key, heap-boxed to avoid a ~24.75 MB
    /// by-value stack transit when the caller hands it over.
    pub lwe_to_rlwe_key: Box<K>,
    /// $\mathrm{RLev}_{S_1}(S_1^2)$ — the RLWE→RGSW conversion key at depth `L_CK`.
    pub rlwe_to_rgsw_key: RLevCiphertext<N1, R1, L_CK>,
}

impl<K: Zeroize, const N1: usize, R1: RingPoly<N1>, const L_CK: usize>
    QueryCompressionKey<K, N1, R1, L_CK>
{
    /// Construct a `QueryCompressionKey` from its two halves. The cascade key
    /// must be supplied box-wrapped (avoids a large by-value stack transit).
    pub fn new(lwe_to_rlwe_key: Box<K>, rlwe_to_rgsw_key: RLevCiphertext<N1, R1, L_CK>) -> Self {
        Self {
            lwe_to_rlwe_key,
            rlwe_to_rgsw_key,
        }
    }
}

impl<K: Zeroize, const N1: usize, R1: RingPoly<N1>, const L_CK: usize> Zeroize
    for QueryCompressionKey<K, N1, R1, L_CK>
{
    fn zeroize(&mut self) {
        self.lwe_to_rlwe_key.zeroize();
        self.rlwe_to_rgsw_key.zeroize();
    }
}

impl<K: Zeroize, const N1: usize, R1: RingPoly<N1>, const L_CK: usize> Drop
    for QueryCompressionKey<K, N1, R1, L_CK>
{
    fn drop(&mut self) {
        self.zeroize();
    }
}

impl<K: Zeroize, const N1: usize, R1: RingPoly<N1>, const L_CK: usize> ZeroizeOnDrop
    for QueryCompressionKey<K, N1, R1, L_CK>
{
}

/// `Debug` redacts both key fields (each is derived from $S_1$).
impl<K: Zeroize, const N1: usize, R1: RingPoly<N1>, const L_CK: usize> fmt::Debug
    for QueryCompressionKey<K, N1, R1, L_CK>
{
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("QueryCompressionKey")
            .field("N1", &N1)
            .field("L_CK", &L_CK)
            .field("lwe_to_rlwe_key", &"<redacted>")
            .field("rlwe_to_rgsw_key", &"<redacted>")
            .finish()
    }
}

// ---------------------------------------------------------------------------
// PublicParams
// ---------------------------------------------------------------------------

/// Full public parameter bundle — the paper `pp = (pp_qck, pp_rck)` plus the
/// database layout (`via_c/params.py:PublicParams`).
///
/// Returned by `via-client::Client::setup`; consumed by
/// `via-server::Server::answer`. Generic over the cascade key type `K`, the
/// large-ring `R1: RingPoly<N1>` (single-prime for the toy path, RNS for the
/// paper path — hence NOT a hardcoded RNS alias), and the ring-switch target
/// `R2: RingPoly<N2>` (the $q_3$ ring per paper Lemma C.5).
///
/// # Panics
///
/// [`PublicParams::new`] panics if `num_rows == 0` or `num_cols == 0`, and in
/// debug builds if the `PIRParams` dims don't match the const preset.
pub struct PublicParams<
    K: Zeroize,
    const N1: usize,
    const N2: usize,
    R1: RingPoly<N1>,
    R2: RingPoly<N2>,
    const L_QUERY: usize,
    const L_CK: usize,
    const L_RSK: usize,
    const D: usize,
> {
    /// Query compression key (`pp_qck`): cascade key + RLev conversion key.
    pub query_comp_key: QueryCompressionKey<K, N1, R1, L_CK>,
    /// Ring-switch key (`pp_rck`): $\mathrm{RSK}_{S_1 \to S_2}$ from
    /// $R_{N_1, q_3}$ to $R_{N_2, q_3}$ (paper Lemma C.5 — the key is built and
    /// operates at $q_3$; the $q_2$ in the security proof's Hyb1 is only the
    /// indistinguishability target, not the generation modulus).
    pub ring_switch_key: RingSwitchKey<N1, N2, R2, L_RSK, D>,
    /// Runtime parameter sidecar (moduli, bases, distributions).
    pub params: PIRParams,
    /// Number of rows $I$ in the database matrix.
    pub num_rows: usize,
    /// Number of columns $J$ in the database matrix.
    pub num_cols: usize,
    /// Conversion-key gadget base $B_\mathrm{ck}$ for RLWE→RGSW. Not carried by
    /// [`PIRParams`] (it is a setup argument, `via_c/params.py:PublicParams`);
    /// the matching depth is the const `L_CK`.
    pub ck_base: u64,
    /// Conversion-key gadget depth $\ell_\mathrm{ck}$ (equals the const `L_CK`).
    pub ck_depth: usize,
}

impl<
    K: Zeroize,
    const N1: usize,
    const N2: usize,
    R1: RingPoly<N1>,
    R2: RingPoly<N2>,
    const L_QUERY: usize,
    const L_CK: usize,
    const L_RSK: usize,
    const D: usize,
> PublicParams<K, N1, N2, R1, R2, L_QUERY, L_CK, L_RSK, D>
{
    /// Construct a `PublicParams`, validating dimensions.
    ///
    /// # Panics
    ///
    /// - If `num_rows == 0` or `num_cols == 0`.
    /// - In debug builds: if `params` dims don't match the const preset.
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        query_comp_key: QueryCompressionKey<K, N1, R1, L_CK>,
        ring_switch_key: RingSwitchKey<N1, N2, R2, L_RSK, D>,
        params: PIRParams,
        num_rows: usize,
        num_cols: usize,
        ck_base: u64,
        ck_depth: usize,
    ) -> Self {
        // Force `_CHECK` evaluation (catches mis-typed alias dims at compile time).
        let () = ViaCPublicParams::<N1, N2, L_QUERY, L_CK, L_RSK, D>::_CHECK;
        // Debug-mode cross-assert with the runtime PIRParams sidecar.
        pir_params_matches_preset::<N1, N2, L_QUERY, L_CK, L_RSK, D>(&params);
        assert!(num_rows > 0, "PublicParams: num_rows must be positive");
        assert!(num_cols > 0, "PublicParams: num_cols must be positive");
        debug_assert_eq!(ck_depth, L_CK, "ck_depth must equal the const L_CK");
        Self {
            query_comp_key,
            ring_switch_key,
            params,
            num_rows,
            num_cols,
            ck_base,
            ck_depth,
        }
    }
}

impl<
    K: Zeroize,
    const N1: usize,
    const N2: usize,
    R1: RingPoly<N1>,
    R2: RingPoly<N2>,
    const L_QUERY: usize,
    const L_CK: usize,
    const L_RSK: usize,
    const D: usize,
> Zeroize for PublicParams<K, N1, N2, R1, R2, L_QUERY, L_CK, L_RSK, D>
{
    fn zeroize(&mut self) {
        self.query_comp_key.zeroize();
        self.ring_switch_key.zeroize();
    }
}

impl<
    K: Zeroize,
    const N1: usize,
    const N2: usize,
    R1: RingPoly<N1>,
    R2: RingPoly<N2>,
    const L_QUERY: usize,
    const L_CK: usize,
    const L_RSK: usize,
    const D: usize,
> fmt::Debug for PublicParams<K, N1, N2, R1, R2, L_QUERY, L_CK, L_RSK, D>
{
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("PublicParams")
            .field("N1", &N1)
            .field("N2", &N2)
            .field("L_QUERY", &L_QUERY)
            .field("L_CK", &L_CK)
            .field("num_rows", &self.num_rows)
            .field("num_cols", &self.num_cols)
            .field("ck_base", &self.ck_base)
            .field("ck_depth", &self.ck_depth)
            .field("query_comp_key", &"<redacted>")
            .field("ring_switch_key", &"<redacted>")
            .finish_non_exhaustive()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::TOY_PARAMS;
    use via_primitives::algebra::rns::basis::paper::ViaCQ1Rns;
    use via_primitives::algebra::zq::modulus::paper::ViaCQ3;
    use via_primitives::encryption::types::RLWECiphertext;
    use via_primitives::params::{ViaCPolyQ1Rns, ViaCPolyQ3};

    // Toy dims (small stack): N1=64, N2=16, L_QUERY=20, L_CK=40, L_RSK=8, D=4.
    const N1: usize = 64;
    const N2: usize = 16;
    const L_CK: usize = 40;
    const L_RSK: usize = 8;
    const D: usize = 4;

    /// Trivial `Zeroize` cascade-key stub (genericity over `K` without P2).
    #[derive(Debug)]
    struct StubKey(u64);
    impl Zeroize for StubKey {
        fn zeroize(&mut self) {
            self.0 = 0;
        }
    }

    fn zero_rlev_q1() -> RLevCiphertext<N1, ViaCPolyQ1Rns<N1>, L_CK> {
        let b = ViaCQ1Rns::default();
        let z = <ViaCPolyQ1Rns<N1> as RingPoly<N1>>::zero(b);
        RLevCiphertext::new([RLWECiphertext::new(z, z); L_CK])
    }

    fn zero_rsk() -> RingSwitchKey<N1, N2, ViaCPolyQ3<N2>, L_RSK, D> {
        let q3 = ViaCQ3::default();
        let z = <ViaCPolyQ3<N2> as RingPoly<N2>>::zero(q3);
        let rlev = RLevCiphertext::new([RLWECiphertext::new(z, z); L_RSK]);
        RingSwitchKey::new([rlev; D])
    }

    #[test]
    fn query_compression_key_constructs_and_debug_redacts() {
        let qck = QueryCompressionKey::<StubKey, N1, ViaCPolyQ1Rns<N1>, L_CK>::new(
            Box::new(StubKey(42)),
            zero_rlev_q1(),
        );
        let dbg = alloc::format!("{qck:?}");
        assert!(dbg.contains("<redacted>"));
        assert!(!dbg.contains("42")); // must not leak the stub value
    }

    #[test]
    fn query_compression_key_zeroize_clears_stub() {
        let mut qck = QueryCompressionKey::<StubKey, N1, ViaCPolyQ1Rns<N1>, L_CK>::new(
            Box::new(StubKey(99)),
            zero_rlev_q1(),
        );
        qck.zeroize();
        assert_eq!(qck.lwe_to_rlwe_key.0, 0, "stub was not zeroized");
    }

    #[test]
    fn public_params_constructs_and_cross_asserts() {
        let qck = QueryCompressionKey::<StubKey, N1, ViaCPolyQ1Rns<N1>, L_CK>::new(
            Box::new(StubKey(7)),
            zero_rlev_q1(),
        );
        // L_QUERY = 20 matches TOY_PARAMS.gadget_depth_1.
        let pp = PublicParams::<
            StubKey,
            N1,
            N2,
            ViaCPolyQ1Rns<N1>,
            ViaCPolyQ3<N2>,
            20,
            L_CK,
            L_RSK,
            D,
        >::new(
            qck,
            zero_rsk(),
            TOY_PARAMS,
            2,    // num_rows = TOY_I
            2,    // num_cols = TOY_J
            2,    // ck_base = TOY_CK_BASE
            L_CK, // ck_depth = TOY_CK_DEPTH = L_CK
        );
        assert_eq!(pp.num_rows, 2);
        assert_eq!(pp.num_cols, 2);
        let dbg = alloc::format!("{pp:?}");
        assert!(dbg.contains("PublicParams"));
        assert!(dbg.contains("<redacted>"));
    }
}
