//! §5.3/§5.4 — the [`crate::lwe_to_rlwe_cascade!`] macro and the toy-parameter
//! cascade instantiations it produces. See `.docs/primitives.md` §5.3-§5.4.
//!
//! The full LWE→RLWE cascade changes **both** the MLWE rank and the ring degree
//! at every step (`(n,1) → (n/2,2) → … → (1,n)`), and both are compile-time
//! const-generics, so it cannot be a runtime loop as in the Python reference
//! (`pir/primitives/mlwe.py:347-383`). Instead [`crate::lwe_to_rlwe_cascade!`] emits,
//! per concrete `n`:
//!
//! - a `LWEToRLWEKey`-style struct with one fixed-size array of RLev step keys
//!   **per step**, each at that step's output degree (the step keys are
//!   heterogeneous in degree, so a single flat array is impossible);
//! - its generator (`gen_*`), one [`super::gen_conv_step_key`] call per step;
//! - the cascade function (`lwe_to_rlwe_n*`), one [`super::conv_step`] per step.
//!
//! Layer 5 instantiates only the toy sizes (`n = 8` for the KAT, `n = 4` as a
//! smoke test, and `n = 8` on the RNS backend). Layer 6 invokes the macro for
//! the paper `n₁`; Layer 7 reuses the same step machinery for §7.3.

/// Generate the degree-`n` LWE→RLWE cascade: a key struct, its generator, and
/// the cascade function (§5.3-§5.4).
///
/// # Invocation
///
/// ```text
/// lwe_to_rlwe_cascade! {
///     n = 8,
///     ring = Poly,                                     // or PolyRns
///     mod_param = M, mod_bound = path::to::Modulus,    // or B / RnsBasis
///     levels = L,
///     key = LweToRlweKeyN8, gen = gen_lwe_to_rlwe_key_n8, cast = lwe_to_rlwe_n8,
///     steps = [
///         //  (field,   RANK_IN, N_IN, RANK_OUT, N_OUT)
///         (keys_2, 8, 1, 4, 2),
///         (keys_4, 4, 2, 2, 4),
///         (keys_8, 2, 4, 1, 8),
///     ],
/// }
/// ```
///
/// Each step tuple `(field, RANK_IN, N_IN, RANK_OUT, N_OUT)` drives all three
/// products: the key field `field: [RLev<N_OUT, Ring<N_OUT>, L>; RANK_IN]`, the
/// generator's [`gen_conv_step_key`](super::gen_conv_step_key) call, and the
/// cascade's [`conv_step`](super::conv_step) call.
#[macro_export]
macro_rules! lwe_to_rlwe_cascade {
    // ===== @chain: fold the steps into a nested conv_step expression =====
    // Base case: no steps left — `$input` is `&<final (1,n)-MLWE>`.
    (@chain ($ring:ident, $modp:ident, $lev:ident, $base:expr, $key:ident) $input:expr ;) => {
        $crate::conversion::mlwe_to_rlwe($input)
    };
    // One step: apply conv_step to `$input`, then recurse on `&<result>`.
    (@chain ($ring:ident, $modp:ident, $lev:ident, $base:expr, $key:ident) $input:expr ;
        ($field:ident, $rin:literal, $nin:literal, $rout:literal, $nout:literal) $($rest:tt)*) => {
        $crate::lwe_to_rlwe_cascade!(@chain ($ring, $modp, $lev, $base, $key)
            &$crate::conversion::conv_step::<
                $rin, $nin, $rout, $nout,
                $ring<$nin, $modp, $crate::algebra::ring::form::Coefficient>,
                $ring<$nout, $modp, $crate::algebra::ring::form::Coefficient>,
                $lev,
            >($input, &$key.$field, $base)
            ; $($rest)*)
    };

    // ===== main entry: emit key struct + generator + cascade fn =====
    (
        n = $n:literal,
        ring = $ring:ident,
        mod_param = $modp:ident,
        mod_bound = $modbound:path,
        levels = $lev:ident,
        key = $key:ident,
        gen = $gen:ident,
        cast = $cast:ident,
        steps = [ $( ($field:ident, $rin:literal, $nin:literal, $rout:literal, $nout:literal) ),+ $(,)? ],
    ) => {
        #[doc = concat!(
            "Cascade key material (the `pp_qck` cascade half) for the degree-",
            stringify!($n),
            " LWE→RLWE conversion (§5.4): one fixed-size array of RLev step keys per ",
            "Conv₂ step, each at that step's output ring degree. Generated by the ",
            "`lwe_to_rlwe_cascade!` macro."
        )]
        pub struct $key<$modp: $modbound, const $lev: usize> {
            $(
                /// Step keys consumed by the matching
                /// [`conv_step`](crate::conversion::conv_step) at this step's
                /// output degree.
                pub $field: [
                    $crate::encryption::RLevCiphertext<
                        $nout,
                        $ring<$nout, $modp, $crate::algebra::ring::form::Coefficient>,
                        $lev,
                    >;
                    $rin
                ],
            )+
        }

        impl<$modp: $modbound, const $lev: usize> ::zeroize::Zeroize for $key<$modp, $lev> {
            fn zeroize(&mut self) {
                $( for s in &mut self.$field { ::zeroize::Zeroize::zeroize(s); } )+
            }
        }

        impl<$modp: $modbound, const $lev: usize> ::core::ops::Drop for $key<$modp, $lev> {
            fn drop(&mut self) {
                ::zeroize::Zeroize::zeroize(self);
            }
        }

        impl<$modp: $modbound, const $lev: usize> ::zeroize::ZeroizeOnDrop for $key<$modp, $lev> {}

        impl<$modp: $modbound, const $lev: usize> ::core::fmt::Debug for $key<$modp, $lev> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                f.debug_struct(stringify!($key))
                    .field("n", &$n)
                    .field("L", &$lev)
                    .finish_non_exhaustive()
            }
        }

        #[doc = concat!(
            "§5.4 — generate the degree-", stringify!($n),
            " cascade key from the single secret key `sk`. Calls ",
            "[`gen_conv_step_key`](crate::conversion::gen_conv_step_key) once per step, in ",
            "ascending output-degree order — the cross-language PRG-order contract."
        )]
        pub fn $gen<$modp: $modbound, const $lev: usize>(
            sk: &$crate::encryption::SecretKey<
                $n,
                $ring<$n, $modp, $crate::algebra::ring::form::Coefficient>,
            >,
            base: u64,
            error_dist: $crate::sampling::distribution::Distribution,
            prg: &mut $crate::sampling::prg::Shake256Prg,
        ) -> $key<$modp, $lev> {
            $key {
                $(
                    $field: $crate::conversion::gen_conv_step_key::<
                        $n, $nin, $nout, $rin,
                        $ring<$n, $modp, $crate::algebra::ring::form::Coefficient>,
                        $lev,
                    >(sk, base, error_dist, prg),
                )+
            }
        }

        #[doc = concat!(
            "§5.3 — run the degree-", stringify!($n),
            " LWE→RLWE cascade: an `(", stringify!($n),
            ", 1)`-MLWE (LWE) becomes a `(1, ", stringify!($n),
            ")`-MLWE (RLWE), via one [`conv_step`](crate::conversion::conv_step) per step."
        )]
        pub fn $cast<$modp: $modbound, const $lev: usize>(
            ct: &$crate::encryption::MLWECiphertext<
                $n, 1, $ring<1, $modp, $crate::algebra::ring::form::Coefficient>,
            >,
            key: &$key<$modp, $lev>,
            base: u64,
        ) -> $crate::encryption::RLWECiphertext<
            $n, $ring<$n, $modp, $crate::algebra::ring::form::Coefficient>,
        > {
            $crate::lwe_to_rlwe_cascade!(@chain ($ring, $modp, $lev, base, key) ct ;
                $( ($field, $rin, $nin, $rout, $nout) )+)
        }
    };
}

// The macro expands the bare `$ring` ident (`Poly` / `PolyRns`) in this scope.
use crate::algebra::ring::element::Poly;
use crate::algebra::ring::rns_element::PolyRns;

// --- Toy single-prime instantiations -------------------------------------

lwe_to_rlwe_cascade! {
    n = 8,
    ring = Poly,
    mod_param = M,
    mod_bound = crate::algebra::zq::modulus::Modulus,
    levels = L,
    key = LweToRlweKeyN8,
    gen = gen_lwe_to_rlwe_key_n8,
    cast = lwe_to_rlwe_n8,
    steps = [
        (keys_2, 8, 1, 4, 2),
        (keys_4, 4, 2, 2, 4),
        (keys_8, 2, 4, 1, 8),
    ],
}

lwe_to_rlwe_cascade! {
    n = 4,
    ring = Poly,
    mod_param = M,
    mod_bound = crate::algebra::zq::modulus::Modulus,
    levels = L,
    key = LweToRlweKeyN4,
    gen = gen_lwe_to_rlwe_key_n4,
    cast = lwe_to_rlwe_n4,
    steps = [
        (keys_2, 4, 1, 2, 2),
        (keys_4, 2, 2, 1, 4),
    ],
}

// The VIA-C toy parameter set (`ViaCToyParams<64, 16, …>`) runs query
// compression at n₁ = 64 on the single-prime backend, so the toy end-to-end
// path uses this degree-64 cascade. Six steps (`log₂ 64`); the n₆₄ key is
// small (~150 KB at L = 12), so it stays by-value / no-alloc — unlike the
// degree-2048 paper instantiation, which needs the boxed builder.
lwe_to_rlwe_cascade! {
    n = 64,
    ring = Poly,
    mod_param = M,
    mod_bound = crate::algebra::zq::modulus::Modulus,
    levels = L,
    key = LweToRlweKeyN64,
    gen = gen_lwe_to_rlwe_key_n64,
    cast = lwe_to_rlwe_n64,
    steps = [
        (keys_2, 64, 1, 32, 2),
        (keys_4, 32, 2, 16, 4),
        (keys_8, 16, 4, 8, 8),
        (keys_16, 8, 8, 4, 16),
        (keys_32, 4, 16, 2, 32),
        (keys_64, 2, 32, 1, 64),
    ],
}

// --- Toy RNS instantiation (paper query compression lives at q₁ RNS) ------

lwe_to_rlwe_cascade! {
    n = 8,
    ring = PolyRns,
    mod_param = B,
    mod_bound = crate::algebra::rns::basis::RnsBasis,
    levels = L,
    key = LweToRlweKeyRnsN8,
    gen = gen_lwe_to_rlwe_key_rns_n8,
    cast = lwe_to_rlwe_rns_n8,
    steps = [
        (keys_2, 8, 1, 4, 2),
        (keys_4, 4, 2, 2, 4),
        (keys_8, 2, 4, 1, 8),
    ],
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::algebra::ring::form::Coefficient;
    use crate::algebra::rns::basis::ConstRnsBasis;
    use crate::algebra::zq::modulus::ConstModulus;
    use crate::conversion::encrypt_lwe;
    use crate::encryption::types::SecretKey;
    use crate::sampling::distribution::Distribution;
    use crate::sampling::prg::Shake256Prg;

    const BASE: u64 = 8;
    const L: usize = 6;
    type R8 = Poly<8, ConstModulus<65537>, Coefficient>;
    type R4 = Poly<4, ConstModulus<65537>, Coefficient>;
    type P8 = Poly<8, ConstModulus<16>, Coefficient>;
    type P4 = Poly<4, ConstModulus<16>, Coefficient>;

    // n = 64 toy cascade. A ~2^34 modulus (the paper ViaCQ2 prime) gives ample
    // noise budget for the 6-step cascade (vs 3 steps at n8); base 8, depth 12
    // (8^12 = 2^36 ≥ 2^34 covers the modulus for gadget representability).
    type R64 = Poly<64, ConstModulus<17175674881>, Coefficient>;
    type P64 = Poly<64, ConstModulus<16>, Coefficient>;
    const BASE_64: u64 = 8;
    const L_64: usize = 12;

    #[test]
    fn cascade_key_count_n8() {
        let q = ConstModulus::<65537>;
        let mut prg = Shake256Prg::new(b"key-count-8");
        let sk = SecretKey::<8, R8>::keygen(q, Distribution::Ternary, &mut prg);
        let key = gen_lwe_to_rlwe_key_n8::<_, L>(&sk, BASE, Distribution::Ternary, &mut prg);
        // 8 + 4 + 2 = 14 = 2·(8−1).
        assert_eq!(key.keys_2.len() + key.keys_4.len() + key.keys_8.len(), 14);
        assert_eq!(key.keys_2.len(), 8);
        assert_eq!(key.keys_4.len(), 4);
        assert_eq!(key.keys_8.len(), 2);
    }

    #[test]
    fn cascade_key_count_n4() {
        let q = ConstModulus::<65537>;
        let mut prg = Shake256Prg::new(b"key-count-4");
        let sk = SecretKey::<4, R4>::keygen(q, Distribution::Ternary, &mut prg);
        let key = gen_lwe_to_rlwe_key_n4::<_, L>(&sk, BASE, Distribution::Ternary, &mut prg);
        // 4 + 2 = 6 = 2·(4−1).
        assert_eq!(key.keys_2.len() + key.keys_4.len(), 6);
    }

    #[test]
    fn cascade_full_roundtrip_n8() {
        let q = ConstModulus::<65537>;
        let p = ConstModulus::<16>;
        for message in 0..16u64 {
            let mut prg = Shake256Prg::new(b"cascade-roundtrip-8");
            let sk = SecretKey::<8, R8>::keygen(q, Distribution::Ternary, &mut prg);
            let lwe = encrypt_lwe(&sk, message, 16, Distribution::Ternary, &mut prg);
            let key = gen_lwe_to_rlwe_key_n8::<_, L>(&sk, BASE, Distribution::Ternary, &mut prg);
            let rlwe = lwe_to_rlwe_n8::<_, L>(&lwe, &key, BASE);
            // The cascade leaves the scalar at coefficient 0 of the degree-8 RLWE.
            let recovered: P8 = sk.decrypt(&rlwe, p);
            assert_eq!(recovered.coeff(0).to_u64(), message, "message {message}");
            for i in 1..8 {
                assert_eq!(
                    recovered.coeff(i).to_u64(),
                    0,
                    "message {message}, coeff {i}"
                );
            }
        }
    }

    #[test]
    fn cascade_full_roundtrip_n4() {
        let q = ConstModulus::<65537>;
        let p = ConstModulus::<16>;
        for message in 0..16u64 {
            let mut prg = Shake256Prg::new(b"cascade-roundtrip-4");
            let sk = SecretKey::<4, R4>::keygen(q, Distribution::Ternary, &mut prg);
            let lwe = encrypt_lwe(&sk, message, 16, Distribution::Ternary, &mut prg);
            let key = gen_lwe_to_rlwe_key_n4::<_, L>(&sk, BASE, Distribution::Ternary, &mut prg);
            let rlwe = lwe_to_rlwe_n4::<_, L>(&lwe, &key, BASE);
            let recovered: P4 = sk.decrypt(&rlwe, p);
            assert_eq!(recovered.coeff(0).to_u64(), message, "n4 message {message}");
        }
    }

    #[test]
    fn cascade_key_count_n64() {
        let q = ConstModulus::<17175674881>;
        let mut prg = Shake256Prg::new(b"key-count-64");
        let sk = SecretKey::<64, R64>::keygen(q, Distribution::Ternary, &mut prg);
        let key = gen_lwe_to_rlwe_key_n64::<_, L_64>(&sk, BASE_64, Distribution::Ternary, &mut prg);
        // 64 + 32 + 16 + 8 + 4 + 2 = 126 = 2·(64−1).
        assert_eq!(
            key.keys_2.len()
                + key.keys_4.len()
                + key.keys_8.len()
                + key.keys_16.len()
                + key.keys_32.len()
                + key.keys_64.len(),
            126,
        );
        assert_eq!(key.keys_2.len(), 64);
        assert_eq!(key.keys_64.len(), 2);
    }

    /// The degree-64 toy end-to-end cascade: every `p = 16` message round-trips
    /// to coefficient 0 with no noise leak (all other coefficients exactly 0).
    /// Key is generated once (degree-64 key is ~150 KB, by value / no-alloc).
    #[test]
    fn cascade_full_roundtrip_n64() {
        let q = ConstModulus::<17175674881>;
        let p = ConstModulus::<16>;
        let mut prg = Shake256Prg::new(b"cascade-roundtrip-64");
        let sk = SecretKey::<64, R64>::keygen(q, Distribution::Ternary, &mut prg);
        let key = gen_lwe_to_rlwe_key_n64::<_, L_64>(&sk, BASE_64, Distribution::Ternary, &mut prg);
        for message in 0..16u64 {
            let lwe = encrypt_lwe(&sk, message, 16, Distribution::Ternary, &mut prg);
            let rlwe = lwe_to_rlwe_n64::<_, L_64>(&lwe, &key, BASE_64);
            let recovered: P64 = sk.decrypt(&rlwe, p);
            assert_eq!(
                recovered.coeff(0).to_u64(),
                message,
                "n64 message {message}"
            );
            for i in 1..64 {
                assert_eq!(
                    recovered.coeff(i).to_u64(),
                    0,
                    "n64 msg {message} coeff {i}"
                );
            }
        }
    }

    #[test]
    fn cascade_determinism() {
        let q = ConstModulus::<65537>;
        let mk = || {
            let mut prg = Shake256Prg::new(b"cascade-det");
            let sk = SecretKey::<8, R8>::keygen(q, Distribution::Ternary, &mut prg);
            gen_lwe_to_rlwe_key_n8::<_, L>(&sk, BASE, Distribution::Ternary, &mut prg)
        };
        let a = mk();
        let b = mk();
        // Same seed ⇒ identical first step-key sample.
        for i in 0..2 {
            assert_eq!(
                a.keys_2[0].samples[0].mask.coeff(i).to_u64(),
                b.keys_2[0].samples[0].mask.coeff(i).to_u64(),
            );
        }
    }

    /// Paper-class: the full cascade on the RNS backend (query compression lives
    /// at the composite q₁). `Q = 7681·12289 ≈ 2^26.5`, enough budget for 3 steps.
    #[test]
    fn cascade_full_roundtrip_rns_n8() {
        type Rns8 = PolyRns<8, ConstRnsBasis<7681, 12289>, Coefficient>;
        let basis = ConstRnsBasis::<7681, 12289>;
        let p = ConstModulus::<16>;
        for message in [0u64, 1, 5, 11, 15] {
            let mut prg = Shake256Prg::new(b"cascade-rns-8");
            let sk = SecretKey::<8, Rns8>::keygen(basis, Distribution::Ternary, &mut prg);
            let lwe = encrypt_lwe(&sk, message, 16, Distribution::Ternary, &mut prg);
            let key =
                gen_lwe_to_rlwe_key_rns_n8::<_, L>(&sk, BASE, Distribution::Ternary, &mut prg);
            let rlwe = lwe_to_rlwe_rns_n8::<_, L>(&lwe, &key, BASE);
            let recovered: P8 = sk.decrypt(&rlwe, p);
            assert_eq!(
                recovered.coeff(0).to_u64(),
                message,
                "rns message {message}"
            );
        }
    }
}

// ---------------------------------------------------------------------------
// Layer-6 SPIKE derisk (intermediate degree).
//
// Validates the conv_step machinery + **depth-18** noise closure at the PAPER
// q₁ basis (`ViaCQ1Rns ≈ 2^75`), base 18, degree **512** (¼ the paper degree).
// 18^18 ≈ 2^75 ≥ q₁ so base/depth cover the modulus exactly. If this closes,
// the only remaining unknown for n=2048 is the extra O(n log n) noise from 4×
// degree. The key (~5.3 MB) is built by value on a large-stack thread (no
// `unsafe`); the n=2048 boxed builder is a separate follow-up.
//
// Heavy (schoolbook O(n²) mult): `#[ignore]`, release-only. Run with:
//   cargo test -p via-primitives --release -- --ignored spike_n512
// ---------------------------------------------------------------------------
#[cfg(test)]
mod spike {
    // `via-primitives` is `#![no_std]`; the test harness links `std`, but we must
    // name it explicitly to reach `std::thread` for the large-stack spawn.
    extern crate std;

    use crate::algebra::ring::element::Poly;
    use crate::algebra::ring::form::Coefficient;
    use crate::algebra::ring::rns_element::PolyRns;
    use crate::algebra::rns::basis::paper::ViaCQ1Rns;
    use crate::algebra::zq::modulus::ConstModulus;
    use crate::conversion::encrypt_lwe;
    use crate::encryption::types::SecretKey;
    use crate::sampling::distribution::Distribution;
    use crate::sampling::prg::Shake256Prg;

    crate::lwe_to_rlwe_cascade! {
        n = 512,
        ring = PolyRns,
        mod_param = B,
        mod_bound = crate::algebra::rns::basis::RnsBasis,
        levels = L,
        key = LweToRlweKeyRnsN512,
        gen = gen_lwe_to_rlwe_key_rns_n512,
        cast = lwe_to_rlwe_rns_n512,
        steps = [
            (keys_2, 512, 1, 256, 2),
            (keys_4, 256, 2, 128, 4),
            (keys_8, 128, 4, 64, 8),
            (keys_16, 64, 8, 32, 16),
            (keys_32, 32, 16, 16, 32),
            (keys_64, 16, 32, 8, 64),
            (keys_128, 8, 64, 4, 128),
            (keys_256, 4, 128, 2, 256),
            (keys_512, 2, 256, 1, 512),
        ],
    }

    /// Depth-18 noise closure at the paper q₁ basis, degree 512. Builds sk + key
    /// once on a 64 MB-stack thread (key ~5.3 MB by value, no `unsafe`), then
    /// round-trips all `p = 16` messages, asserting the scalar lands at coeff 0
    /// and every other coefficient is exactly 0 (no noise leak).
    #[test]
    #[ignore = "heavy depth-18 RNS cascade; run: cargo test -p via-primitives --release -- --ignored spike_n512"]
    fn spike_n512_depth18_noise_closes() {
        const BASE: u64 = 18;
        const LV: usize = 18;
        type RnsQ1 = PolyRns<512, ViaCQ1Rns, Coefficient>;
        type P512 = Poly<512, ConstModulus<16>, Coefficient>;

        let handle = std::thread::Builder::new()
            .stack_size(64 << 20)
            .spawn(|| {
                let basis = ViaCQ1Rns::default();
                let p = ConstModulus::<16>;
                let mut prg = Shake256Prg::new(b"spike-n512-depth18");
                let sk = SecretKey::<512, RnsQ1>::keygen(basis, Distribution::Ternary, &mut prg);
                let key = gen_lwe_to_rlwe_key_rns_n512::<_, LV>(
                    &sk,
                    BASE,
                    Distribution::Ternary,
                    &mut prg,
                );
                for message in 0..16u64 {
                    let lwe = encrypt_lwe(&sk, message, 16, Distribution::Ternary, &mut prg);
                    let rlwe = lwe_to_rlwe_rns_n512::<_, LV>(&lwe, &key, BASE);
                    let recovered: P512 = sk.decrypt(&rlwe, p);
                    assert_eq!(recovered.coeff(0).to_u64(), message, "n512 msg {message}");
                    for i in 1..512 {
                        assert_eq!(
                            recovered.coeff(i).to_u64(),
                            0,
                            "n512 msg {message} coeff {i} (noise leak)"
                        );
                    }
                }
            })
            .expect("spawn spike thread");
        handle
            .join()
            .expect("spike thread panicked (noise did not close?)");
    }

    // ----- The real thing: full paper degree n = 2048, depth 18 -----

    crate::lwe_to_rlwe_cascade! {
        n = 2048,
        ring = PolyRns,
        mod_param = B,
        mod_bound = crate::algebra::rns::basis::RnsBasis,
        levels = L,
        key = LweToRlweKeyRnsN2048,
        gen = gen_lwe_to_rlwe_key_rns_n2048,
        cast = lwe_to_rlwe_rns_n2048,
        steps = [
            (keys_2, 2048, 1, 1024, 2),
            (keys_4, 1024, 2, 512, 4),
            (keys_8, 512, 4, 256, 8),
            (keys_16, 256, 8, 128, 16),
            (keys_32, 128, 16, 64, 32),
            (keys_64, 64, 32, 32, 64),
            (keys_128, 32, 64, 16, 128),
            (keys_256, 16, 128, 8, 256),
            (keys_512, 8, 256, 4, 512),
            (keys_1024, 4, 512, 2, 1024),
            (keys_2048, 2, 1024, 1, 2048),
        ],
    }

    /// **The depth-18 SPIKE (R1 GO/NO-GO).** Full paper degree n = 2048 at the
    /// paper q₁ basis, base 18, depth 18. Builds sk + key once on a 256 MB-stack
    /// thread (key ~24.75 MB **by value**, no `unsafe` — the production
    /// field-by-field `Box::new_uninit` builder is a separate follow-up), then
    /// round-trips all `p = 16` messages, asserting the scalar lands at coeff 0
    /// and every other coefficient is exactly 0 (no noise leak). PASS ⇒ paper
    /// path GO; panic ⇒ NO-GO (escalate to the L=20/B=16 param search).
    #[test]
    #[ignore = "very heavy depth-18 RNS cascade at n=2048; run: cargo test -p via-primitives --release -- --ignored spike_n2048"]
    fn spike_n2048_depth18_noise_closes() {
        const BASE: u64 = 18;
        const LV: usize = 18;
        type RnsQ1 = PolyRns<2048, ViaCQ1Rns, Coefficient>;
        type P2048 = Poly<2048, ConstModulus<16>, Coefficient>;

        let handle = std::thread::Builder::new()
            .stack_size(256 << 20)
            .spawn(|| {
                let basis = ViaCQ1Rns::default();
                let p = ConstModulus::<16>;
                let mut prg = Shake256Prg::new(b"spike-n2048-depth18");
                let sk = SecretKey::<2048, RnsQ1>::keygen(basis, Distribution::Ternary, &mut prg);
                let key = gen_lwe_to_rlwe_key_rns_n2048::<_, LV>(
                    &sk,
                    BASE,
                    Distribution::Ternary,
                    &mut prg,
                );
                for message in 0..16u64 {
                    let lwe = encrypt_lwe(&sk, message, 16, Distribution::Ternary, &mut prg);
                    let rlwe = lwe_to_rlwe_rns_n2048::<_, LV>(&lwe, &key, BASE);
                    let recovered: P2048 = sk.decrypt(&rlwe, p);
                    assert_eq!(recovered.coeff(0).to_u64(), message, "n2048 msg {message}");
                    for i in 1..2048 {
                        assert_eq!(
                            recovered.coeff(i).to_u64(),
                            0,
                            "n2048 msg {message} coeff {i} (noise leak)"
                        );
                    }
                }
            })
            .expect("spawn spike thread");
        handle
            .join()
            .expect("spike thread panicked (depth-18 noise did NOT close — NO-GO)");
    }
}
