//! §5.3/§5.4 — the [`crate::lwe_to_rlwe_cascade!`] macro and the toy-parameter
//! cascade instantiations it produces. See `.docs/primitives.md` §5.3-§5.4.
//!
//! The full LWE→RLWE cascade changes **both** the MLWE rank and the ring degree
//! at every step (`(n,1) → (n/2,2) → … → (1,n)`), and both are compile-time
//! const-generics, so it cannot be a runtime loop as in the Python reference
//! (`pir/primitives/mlwe.py:347-383`). Instead [`crate::lwe_to_rlwe_cascade!`] emits,
//! per concrete `n`:
//!
//! - a `LWEToRLWEKey`-style struct with one fixed-size array of RLev step keys
//!   **per step**, each at that step's output degree (the step keys are
//!   heterogeneous in degree, so a single flat array is impossible);
//! - its generator (`gen_*`), one [`super::gen_conv_step_key`] call per step;
//! - the cascade function (`lwe_to_rlwe_n*`), one [`super::conv_step`] per step.
//!
//! Layer 5 instantiates only the toy sizes (`n = 8` for the KAT, `n = 4` as a
//! smoke test, and `n = 8` on the RNS backend). Layer 6 invokes the macro for
//! the paper `n₁`; Layer 7 reuses the same step machinery for §7.3.

/// Generate the degree-`n` LWE→RLWE cascade: a key struct, its generator, and
/// the cascade function (§5.3-§5.4).
///
/// # Invocation
///
/// ```text
/// lwe_to_rlwe_cascade! {
///     n = 8,
///     ring = Poly,                                     // or PolyRns
///     mod_param = M, mod_bound = path::to::Modulus,    // or B / RnsBasis
///     levels = L,
///     key = LweToRlweKeyN8, gen = gen_lwe_to_rlwe_key_n8, cast = lwe_to_rlwe_n8,
///     steps = [
///         //  (field,   RANK_IN, N_IN, RANK_OUT, N_OUT)
///         (keys_2, 8, 1, 4, 2),
///         (keys_4, 4, 2, 2, 4),
///         (keys_8, 2, 4, 1, 8),
///     ],
/// }
/// ```
///
/// Each step tuple `(field, RANK_IN, N_IN, RANK_OUT, N_OUT)` drives all three
/// products: the key field `field: [RLev<N_OUT, Ring<N_OUT>, L>; RANK_IN]`, the
/// generator's [`gen_conv_step_key`](super::gen_conv_step_key) call, and the
/// cascade's [`conv_step`](super::conv_step) call.
#[macro_export]
macro_rules! lwe_to_rlwe_cascade {
    // ===== @chain: fold the steps into a nested conv_step expression =====
    // Base case: no steps left — `$input` is `&<final (1,n)-MLWE>`.
    (@chain ($ring:ident, $modp:ident, $lev:ident, $base:expr, $key:ident) $input:expr ;) => {
        $crate::conversion::mlwe_to_rlwe($input)
    };
    // One step: apply conv_step to `$input`, then recurse on `&<result>`.
    (@chain ($ring:ident, $modp:ident, $lev:ident, $base:expr, $key:ident) $input:expr ;
        ($field:ident, $rin:literal, $nin:literal, $rout:literal, $nout:literal) $($rest:tt)*) => {
        $crate::lwe_to_rlwe_cascade!(@chain ($ring, $modp, $lev, $base, $key)
            &$crate::conversion::conv_step::<
                $rin, $nin, $rout, $nout,
                $ring<$nin, $modp, $crate::algebra::ring::form::Coefficient>,
                $ring<$nout, $modp, $crate::algebra::ring::form::Coefficient>,
                $lev,
            >($input, &$key.$field, $base)
            ; $($rest)*)
    };

    // ===== main entry: emit key struct + generator + cascade fn =====
    (
        n = $n:literal,
        ring = $ring:ident,
        mod_param = $modp:ident,
        mod_bound = $modbound:path,
        levels = $lev:ident,
        key = $key:ident,
        gen = $gen:ident,
        cast = $cast:ident,
        steps = [ $( ($field:ident, $rin:literal, $nin:literal, $rout:literal, $nout:literal) ),+ $(,)? ],
    ) => {
        #[doc = concat!(
            "Cascade key material (the `pp_qck` cascade half) for the degree-",
            stringify!($n),
            " LWE→RLWE conversion (§5.4): one fixed-size array of RLev step keys per ",
            "Conv₂ step, each at that step's output ring degree. Generated by the ",
            "`lwe_to_rlwe_cascade!` macro."
        )]
        pub struct $key<$modp: $modbound, const $lev: usize> {
            $(
                /// Step keys consumed by the matching
                /// [`conv_step`](crate::conversion::conv_step) at this step's
                /// output degree.
                pub $field: [
                    $crate::encryption::RLevCiphertext<
                        $nout,
                        $ring<$nout, $modp, $crate::algebra::ring::form::Coefficient>,
                        $lev,
                    >;
                    $rin
                ],
            )+
        }

        impl<$modp: $modbound, const $lev: usize> ::zeroize::Zeroize for $key<$modp, $lev> {
            fn zeroize(&mut self) {
                $( for s in &mut self.$field { ::zeroize::Zeroize::zeroize(s); } )+
            }
        }

        impl<$modp: $modbound, const $lev: usize> ::core::ops::Drop for $key<$modp, $lev> {
            fn drop(&mut self) {
                ::zeroize::Zeroize::zeroize(self);
            }
        }

        impl<$modp: $modbound, const $lev: usize> ::zeroize::ZeroizeOnDrop for $key<$modp, $lev> {}

        impl<$modp: $modbound, const $lev: usize> ::core::fmt::Debug for $key<$modp, $lev> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                f.debug_struct(stringify!($key))
                    .field("n", &$n)
                    .field("L", &$lev)
                    .finish_non_exhaustive()
            }
        }

        #[doc = concat!(
            "§5.4 — generate the degree-", stringify!($n),
            " cascade key from the single secret key `sk`. Calls ",
            "[`gen_conv_step_key`](crate::conversion::gen_conv_step_key) once per step, in ",
            "ascending output-degree order — the cross-language PRG-order contract."
        )]
        pub fn $gen<$modp: $modbound, const $lev: usize>(
            sk: &$crate::encryption::SecretKey<
                $n,
                $ring<$n, $modp, $crate::algebra::ring::form::Coefficient>,
            >,
            base: u64,
            error_dist: $crate::sampling::distribution::Distribution,
            prg: &mut $crate::sampling::prg::Shake256Prg,
        ) -> $key<$modp, $lev> {
            $key {
                $(
                    $field: $crate::conversion::gen_conv_step_key::<
                        $n, $nin, $nout, $rin,
                        $ring<$n, $modp, $crate::algebra::ring::form::Coefficient>,
                        $lev,
                    >(sk, base, error_dist, prg),
                )+
            }
        }

        #[doc = concat!(
            "§5.3 — run the degree-", stringify!($n),
            " LWE→RLWE cascade: an `(", stringify!($n),
            ", 1)`-MLWE (LWE) becomes a `(1, ", stringify!($n),
            ")`-MLWE (RLWE), via one [`conv_step`](crate::conversion::conv_step) per step."
        )]
        pub fn $cast<$modp: $modbound, const $lev: usize>(
            ct: &$crate::encryption::MLWECiphertext<
                $n, 1, $ring<1, $modp, $crate::algebra::ring::form::Coefficient>,
            >,
            key: &$key<$modp, $lev>,
            base: u64,
        ) -> $crate::encryption::RLWECiphertext<
            $n, $ring<$n, $modp, $crate::algebra::ring::form::Coefficient>,
        > {
            $crate::lwe_to_rlwe_cascade!(@chain ($ring, $modp, $lev, base, key) ct ;
                $( ($field, $rin, $nin, $rout, $nout) )+)
        }
    };
}

// The macro expands the bare `$ring` ident (`Poly` / `PolyRns`) in this scope.
use crate::algebra::ring::element::Poly;
use crate::algebra::ring::rns_element::PolyRns;

// --- Toy single-prime instantiations -------------------------------------

lwe_to_rlwe_cascade! {
    n = 8,
    ring = Poly,
    mod_param = M,
    mod_bound = crate::algebra::zq::modulus::Modulus,
    levels = L,
    key = LweToRlweKeyN8,
    gen = gen_lwe_to_rlwe_key_n8,
    cast = lwe_to_rlwe_n8,
    steps = [
        (keys_2, 8, 1, 4, 2),
        (keys_4, 4, 2, 2, 4),
        (keys_8, 2, 4, 1, 8),
    ],
}

lwe_to_rlwe_cascade! {
    n = 4,
    ring = Poly,
    mod_param = M,
    mod_bound = crate::algebra::zq::modulus::Modulus,
    levels = L,
    key = LweToRlweKeyN4,
    gen = gen_lwe_to_rlwe_key_n4,
    cast = lwe_to_rlwe_n4,
    steps = [
        (keys_2, 4, 1, 2, 2),
        (keys_4, 2, 2, 1, 4),
    ],
}

// --- Toy RNS instantiation (paper query compression lives at q₁ RNS) ------

lwe_to_rlwe_cascade! {
    n = 8,
    ring = PolyRns,
    mod_param = B,
    mod_bound = crate::algebra::rns::basis::RnsBasis,
    levels = L,
    key = LweToRlweKeyRnsN8,
    gen = gen_lwe_to_rlwe_key_rns_n8,
    cast = lwe_to_rlwe_rns_n8,
    steps = [
        (keys_2, 8, 1, 4, 2),
        (keys_4, 4, 2, 2, 4),
        (keys_8, 2, 4, 1, 8),
    ],
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::algebra::ring::form::Coefficient;
    use crate::algebra::rns::basis::ConstRnsBasis;
    use crate::algebra::zq::modulus::ConstModulus;
    use crate::conversion::encrypt_lwe;
    use crate::encryption::types::SecretKey;
    use crate::sampling::distribution::Distribution;
    use crate::sampling::prg::Shake256Prg;

    const BASE: u64 = 8;
    const L: usize = 6;
    type R8 = Poly<8, ConstModulus<65537>, Coefficient>;
    type R4 = Poly<4, ConstModulus<65537>, Coefficient>;
    type P8 = Poly<8, ConstModulus<16>, Coefficient>;
    type P4 = Poly<4, ConstModulus<16>, Coefficient>;

    #[test]
    fn cascade_key_count_n8() {
        let q = ConstModulus::<65537>;
        let mut prg = Shake256Prg::new(b"key-count-8");
        let sk = SecretKey::<8, R8>::keygen(q, Distribution::Ternary, &mut prg);
        let key = gen_lwe_to_rlwe_key_n8::<_, L>(&sk, BASE, Distribution::Ternary, &mut prg);
        // 8 + 4 + 2 = 14 = 2·(8−1).
        assert_eq!(key.keys_2.len() + key.keys_4.len() + key.keys_8.len(), 14);
        assert_eq!(key.keys_2.len(), 8);
        assert_eq!(key.keys_4.len(), 4);
        assert_eq!(key.keys_8.len(), 2);
    }

    #[test]
    fn cascade_key_count_n4() {
        let q = ConstModulus::<65537>;
        let mut prg = Shake256Prg::new(b"key-count-4");
        let sk = SecretKey::<4, R4>::keygen(q, Distribution::Ternary, &mut prg);
        let key = gen_lwe_to_rlwe_key_n4::<_, L>(&sk, BASE, Distribution::Ternary, &mut prg);
        // 4 + 2 = 6 = 2·(4−1).
        assert_eq!(key.keys_2.len() + key.keys_4.len(), 6);
    }

    #[test]
    fn cascade_full_roundtrip_n8() {
        let q = ConstModulus::<65537>;
        let p = ConstModulus::<16>;
        for message in 0..16u64 {
            let mut prg = Shake256Prg::new(b"cascade-roundtrip-8");
            let sk = SecretKey::<8, R8>::keygen(q, Distribution::Ternary, &mut prg);
            let lwe = encrypt_lwe(&sk, message, 16, Distribution::Ternary, &mut prg);
            let key = gen_lwe_to_rlwe_key_n8::<_, L>(&sk, BASE, Distribution::Ternary, &mut prg);
            let rlwe = lwe_to_rlwe_n8::<_, L>(&lwe, &key, BASE);
            // The cascade leaves the scalar at coefficient 0 of the degree-8 RLWE.
            let recovered: P8 = sk.decrypt(&rlwe, p);
            assert_eq!(recovered.coeff(0).to_u64(), message, "message {message}");
            for i in 1..8 {
                assert_eq!(
                    recovered.coeff(i).to_u64(),
                    0,
                    "message {message}, coeff {i}"
                );
            }
        }
    }

    #[test]
    fn cascade_full_roundtrip_n4() {
        let q = ConstModulus::<65537>;
        let p = ConstModulus::<16>;
        for message in 0..16u64 {
            let mut prg = Shake256Prg::new(b"cascade-roundtrip-4");
            let sk = SecretKey::<4, R4>::keygen(q, Distribution::Ternary, &mut prg);
            let lwe = encrypt_lwe(&sk, message, 16, Distribution::Ternary, &mut prg);
            let key = gen_lwe_to_rlwe_key_n4::<_, L>(&sk, BASE, Distribution::Ternary, &mut prg);
            let rlwe = lwe_to_rlwe_n4::<_, L>(&lwe, &key, BASE);
            let recovered: P4 = sk.decrypt(&rlwe, p);
            assert_eq!(recovered.coeff(0).to_u64(), message, "n4 message {message}");
        }
    }

    #[test]
    fn cascade_determinism() {
        let q = ConstModulus::<65537>;
        let mk = || {
            let mut prg = Shake256Prg::new(b"cascade-det");
            let sk = SecretKey::<8, R8>::keygen(q, Distribution::Ternary, &mut prg);
            gen_lwe_to_rlwe_key_n8::<_, L>(&sk, BASE, Distribution::Ternary, &mut prg)
        };
        let a = mk();
        let b = mk();
        // Same seed ⇒ identical first step-key sample.
        for i in 0..2 {
            assert_eq!(
                a.keys_2[0].samples[0].mask.coeff(i).to_u64(),
                b.keys_2[0].samples[0].mask.coeff(i).to_u64(),
            );
        }
    }

    /// Paper-class: the full cascade on the RNS backend (query compression lives
    /// at the composite q₁). `Q = 7681·12289 ≈ 2^26.5`, enough budget for 3 steps.
    #[test]
    fn cascade_full_roundtrip_rns_n8() {
        type Rns8 = PolyRns<8, ConstRnsBasis<7681, 12289>, Coefficient>;
        let basis = ConstRnsBasis::<7681, 12289>;
        let p = ConstModulus::<16>;
        for message in [0u64, 1, 5, 11, 15] {
            let mut prg = Shake256Prg::new(b"cascade-rns-8");
            let sk = SecretKey::<8, Rns8>::keygen(basis, Distribution::Ternary, &mut prg);
            let lwe = encrypt_lwe(&sk, message, 16, Distribution::Ternary, &mut prg);
            let key =
                gen_lwe_to_rlwe_key_rns_n8::<_, L>(&sk, BASE, Distribution::Ternary, &mut prg);
            let rlwe = lwe_to_rlwe_rns_n8::<_, L>(&lwe, &key, BASE);
            let recovered: P8 = sk.decrypt(&rlwe, p);
            assert_eq!(
                recovered.coeff(0).to_u64(),
                message,
                "rns message {message}"
            );
        }
    }
}
