//! §5.3/§5.4 — the [`crate::lwe_to_rlwe_cascade!`] macro and the toy-parameter
//! cascade instantiations it produces. See `.docs/primitives.md` §5.3-§5.4.
//!
//! The full LWE→RLWE cascade changes **both** the MLWE rank and the ring degree
//! at every step (`(n,1) → (n/2,2) → … → (1,n)`), and both are compile-time
//! const-generics, so it cannot be a runtime loop as in the Python reference
//! (`pir/primitives/mlwe.py:347-383`). Instead [`crate::lwe_to_rlwe_cascade!`] emits,
//! per concrete `n`:
//!
//! - a `LWEToRLWEKey`-style struct with one fixed-size array of RLev step keys
//!   **per step**, each at that step's output degree (the step keys are
//!   heterogeneous in degree, so a single flat array is impossible);
//! - its generator (`gen_*`), one [`super::gen_conv_step_key`] call per step;
//! - the cascade function (`lwe_to_rlwe_n*`), one [`super::conv_step`] per step.
//!
//! Layer 5 instantiates only the toy sizes (`n = 8` for the KAT, `n = 4` as a
//! smoke test, and `n = 8` on the RNS backend). Layer 6 invokes the macro for
//! the paper `n₁`; Layer 7 reuses the same step machinery for §7.3.

/// Generate the degree-`n` LWE→RLWE cascade: a key struct, its generator, and
/// the cascade function (§5.3-§5.4).
///
/// # Invocation
///
/// ```text
/// lwe_to_rlwe_cascade! {
///     n = 8,
///     ring = Poly,                                     // or PolyRns
///     mod_param = M, mod_bound = path::to::Modulus,    // or B / RnsBasis
///     levels = L,
///     key = LweToRlweKeyN8, gen = gen_lwe_to_rlwe_key_n8, cast = lwe_to_rlwe_n8,
///     steps = [
///         //  (field,   RANK_IN, N_IN, RANK_OUT, N_OUT)
///         (keys_2, 8, 1, 4, 2),
///         (keys_4, 4, 2, 2, 4),
///         (keys_8, 2, 4, 1, 8),
///     ],
/// }
/// ```
///
/// Each step tuple `(field, RANK_IN, N_IN, RANK_OUT, N_OUT)` drives all three
/// products: the key field `field: [RLev<N_OUT, Ring<N_OUT>, L>; RANK_IN]`, the
/// generator's [`gen_conv_step_key`](super::gen_conv_step_key) call, and the
/// cascade's [`conv_step`](super::conv_step) call.
#[macro_export]
macro_rules! lwe_to_rlwe_cascade {
    // ===== @chain: fold the steps into a nested conv_step expression =====
    // Base case: no steps left — `$input` is `&<final (1,n)-MLWE>`.
    (@chain ($ring:ident, $modp:ident, $lev:ident, $base:expr, $key:ident) $input:expr ;) => {
        $crate::conversion::mlwe_to_rlwe($input)
    };
    // One step: apply conv_step to `$input`, then recurse on `&<result>`.
    (@chain ($ring:ident, $modp:ident, $lev:ident, $base:expr, $key:ident) $input:expr ;
        ($field:ident, $rin:literal, $nin:literal, $rout:literal, $nout:literal) $($rest:tt)*) => {
        $crate::lwe_to_rlwe_cascade!(@chain ($ring, $modp, $lev, $base, $key)
            &$crate::conversion::conv_step::<
                $rin, $nin, $rout, $nout,
                $ring<$nin, $modp, $crate::algebra::ring::form::Coefficient>,
                $ring<$nout, $modp, $crate::algebra::ring::form::Coefficient>,
                $lev,
            >($input, &$key.$field, $base)
            ; $($rest)*)
    };

    // ===== @chain_eval: like @chain but eval-form step keys (conv_step_eval) =====
    (@chain_eval ($ring:ident, $modp:ident, $lev:ident, $base:expr, $key:ident) $input:expr ;) => {
        $crate::conversion::mlwe_to_rlwe($input)
    };
    (@chain_eval ($ring:ident, $modp:ident, $lev:ident, $base:expr, $key:ident) $input:expr ;
        ($field:ident, $rin:literal, $nin:literal, $rout:literal, $nout:literal) $($rest:tt)*) => {
        $crate::lwe_to_rlwe_cascade!(@chain_eval ($ring, $modp, $lev, $base, $key)
            &$crate::conversion::conv_step_eval::<
                $rin, $nin, $rout, $nout,
                $ring<$nin, $modp, $crate::algebra::ring::form::Coefficient>,
                $ring<$nout, $modp, $crate::algebra::ring::form::Coefficient>,
                $lev,
            >($input, &$key.$field, $base)
            ; $($rest)*)
    };

    // ===== main entry: emit key struct + generator + cascade fn =====
    (
        n = $n:literal,
        ring = $ring:ident,
        mod_param = $modp:ident,
        mod_bound = $modbound:path,
        levels = $lev:ident,
        key = $key:ident,
        gen = $gen:ident,
        gen_boxed = $genb:ident,
        cast = $cast:ident,
        eval_key = $ekey:ident,
        cast_eval = $casteval:ident,
        steps = [ $( ($field:ident, $rin:literal, $nin:literal, $rout:literal, $nout:literal) ),+ $(,)? ],
    ) => {
        #[doc = concat!(
            "Cascade key material (the `pp_qck` cascade half) for the degree-",
            stringify!($n),
            " LWE→RLWE conversion (§5.4): one fixed-size array of RLev step keys per ",
            "Conv₂ step, each at that step's output ring degree. Generated by the ",
            "`lwe_to_rlwe_cascade!` macro."
        )]
        pub struct $key<$modp: $modbound, const $lev: usize> {
            $(
                /// Step keys consumed by the matching
                /// [`conv_step`](crate::conversion::conv_step) at this step's
                /// output degree.
                pub $field: [
                    $crate::encryption::RLevCiphertext<
                        $nout,
                        $ring<$nout, $modp, $crate::algebra::ring::form::Coefficient>,
                        $lev,
                    >;
                    $rin
                ],
            )+
        }

        impl<$modp: $modbound, const $lev: usize> ::zeroize::Zeroize for $key<$modp, $lev> {
            fn zeroize(&mut self) {
                $( for s in &mut self.$field { ::zeroize::Zeroize::zeroize(s); } )+
            }
        }

        impl<$modp: $modbound, const $lev: usize> ::core::ops::Drop for $key<$modp, $lev> {
            fn drop(&mut self) {
                ::zeroize::Zeroize::zeroize(self);
            }
        }

        impl<$modp: $modbound, const $lev: usize> ::zeroize::ZeroizeOnDrop for $key<$modp, $lev> {}

        impl<$modp: $modbound, const $lev: usize> ::core::fmt::Debug for $key<$modp, $lev> {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                f.debug_struct(stringify!($key))
                    .field("n", &$n)
                    .field("L", &$lev)
                    .finish_non_exhaustive()
            }
        }

        #[doc = concat!(
            "§5.4 — generate the degree-", stringify!($n),
            " cascade key **by value** from the single secret key `sk`. Calls ",
            "[`gen_conv_step_key`](crate::conversion::gen_conv_step_key) once per step, in ",
            "ascending output-degree order — the cross-language PRG-order contract.\n\n",
            "The whole key is returned on the stack; for large degrees whose key exceeds a ",
            "thread stack (e.g. n=2048, ~24.75 MB) use [`", stringify!($genb),
            "`] (the heap builder) instead."
        )]
        pub fn $gen<$modp: $modbound, const $lev: usize>(
            sk: &$crate::encryption::SecretKey<
                $n,
                $ring<$n, $modp, $crate::algebra::ring::form::Coefficient>,
            >,
            base: u64,
            error_dist: $crate::sampling::distribution::Distribution,
            prg: &mut $crate::sampling::prg::Shake256Prg,
        ) -> $key<$modp, $lev> {
            $key {
                $(
                    $field: $crate::conversion::gen_conv_step_key::<
                        $n, $nin, $nout, $rin,
                        $ring<$n, $modp, $crate::algebra::ring::form::Coefficient>,
                        $lev,
                    >(sk, base, error_dist, prg),
                )+
            }
        }

        #[cfg(feature = "alloc")]
        #[doc = concat!(
            "§5.4 — heap-build the degree-", stringify!($n),
            " cascade key **one step key at a time** into an uninitialised `Box`, so the ",
            "whole (potentially ~24.75 MB at n=2048) key **never transits the stack** — peak ",
            "stack stays at a single `RLev` (the per-field temporaries reuse one slot and sum ",
            "to only ~2.36 MB across all degrees). The required constructor for large keys: a ",
            "whole-array-per-field write would accumulate to the full key size (RLev `Drop` glue ",
            "defeats slot reuse) and overflow the stack. Draws PRG bytes in the **same order** as ",
            "[`", stringify!($gen), "`], so the two produce identical keys."
        )]
        // The metavariables used inside the `unsafe` block below are the field
        // ident, step literals, ring/modulus types, and this fn's own params —
        // none are caller-injected expressions, so the macro cannot smuggle
        // unsafe code into a caller.
        #[allow(clippy::macro_metavars_in_unsafe)]
        pub fn $genb<$modp: $modbound, const $lev: usize>(
            sk: &$crate::encryption::SecretKey<
                $n,
                $ring<$n, $modp, $crate::algebra::ring::form::Coefficient>,
            >,
            base: u64,
            error_dist: $crate::sampling::distribution::Distribution,
            prg: &mut $crate::sampling::prg::Shake256Prg,
        ) -> ::alloc::boxed::Box<$key<$modp, $lev>> {
            let mut boxed = ::alloc::boxed::Box::<$key<$modp, $lev>>::new_uninit();
            let ptr = boxed.as_mut_ptr();
            // SAFETY: every element of every field is written exactly once, in
            // `(field, key_idx)` declaration order, so the whole `*ptr` is
            // initialised before `assume_init`. We write **one `RLev` at a time**
            // straight into its heap slot via `addr_of_mut!`, never forming a
            // reference to uninitialised memory. Because each loop reuses its
            // single `rlev` stack slot, peak stack stays at one step key (the
            // per-field temporaries sum to ~2.36 MB across all degrees) instead
            // of the whole ~24.75 MB key — a whole-array write per field does NOT
            // share stack slots (the `RLev` `Drop` glue defeats reuse), so it
            // would accumulate to the full key size and overflow the stack.
            unsafe {
                $(
                    for key_idx in 0..$rin {
                        // Write each step-key RLev **straight into its heap slot**,
                        // one RLWE sample at a time — so even the largest single
                        // step key (~1.125 MB at the high-degree n=2048 steps) is
                        // never assembled on the stack. Peak stack is one RLWE.
                        $crate::conversion::gen_conv_step_key_element_into::<
                            $n, $nin, $nout, $rin,
                            $ring<$n, $modp, $crate::algebra::ring::form::Coefficient>,
                            $lev,
                        >(
                            sk,
                            key_idx,
                            base,
                            error_dist,
                            prg,
                            ::core::ptr::addr_of_mut!((*ptr).$field[key_idx]),
                        );
                    }
                )+
                boxed.assume_init()
            }
        }

        #[doc = concat!(
            "§5.3 — run the degree-", stringify!($n),
            " LWE→RLWE cascade: an `(", stringify!($n),
            ", 1)`-MLWE (LWE) becomes a `(1, ", stringify!($n),
            ")`-MLWE (RLWE), via one [`conv_step`](crate::conversion::conv_step) per step."
        )]
        pub fn $cast<$modp: $modbound, const $lev: usize>(
            ct: &$crate::encryption::MLWECiphertext<
                $n, 1, $ring<1, $modp, $crate::algebra::ring::form::Coefficient>,
            >,
            key: &$key<$modp, $lev>,
            base: u64,
        ) -> $crate::encryption::RLWECiphertext<
            $n, $ring<$n, $modp, $crate::algebra::ring::form::Coefficient>,
        >
        where
            // Each step's output ring drives a `conv_step` whose internal
            // `key_switch` is eval-form: real NTT at NTT-friendly moduli (the
            // paper RNS q1), schoolbook identity-fallback otherwise (toy
            // `DynModulus`). A plain `RingPolyEval` bound suffices — the trait is
            // standalone, so it does not shadow `conv_step`'s `RingPoly`
            // `Embedded`/`Modulus` normalisation.
            $(
                $ring<$nout, $modp, $crate::algebra::ring::form::Coefficient>:
                    $crate::algebra::ring::RingPolyEval<$nout>,
            )+
        {
            $crate::lwe_to_rlwe_cascade!(@chain ($ring, $modp, $lev, base, key) ct ;
                $( ($field, $rin, $nin, $rout, $nout) )+)
        }

        // ===== T7 eval-key mirror: pre-transformed step keys + eval cascade =====

        #[doc = concat!(
            "Evaluation-form mirror of [`", stringify!($key), "`] (T7): every step key ",
            "pre-transformed to [`RLevEval`](crate::encryption::RLevEval). Built once via ",
            "[`CascadeKey::to_eval_boxed`](crate::conversion::CascadeKey::to_eval_boxed); ",
            "consumed by [`", stringify!($casteval), "`]. `ZeroizeOnDrop` (secret-derived)."
        )]
        pub struct $ekey<$modp: $modbound, const $lev: usize>
        where
            $(
                $ring<$nout, $modp, $crate::algebra::ring::form::Coefficient>:
                    $crate::algebra::ring::RingPolyEval<$nout>,
            )+
        {
            $(
                pub(crate) $field: [
                    $crate::encryption::RLevEval<
                        $nout,
                        $ring<$nout, $modp, $crate::algebra::ring::form::Coefficient>,
                        $lev,
                    >;
                    $rin
                ],
            )+
        }

        impl<$modp: $modbound, const $lev: usize> ::zeroize::Zeroize for $ekey<$modp, $lev>
        where
            $(
                $ring<$nout, $modp, $crate::algebra::ring::form::Coefficient>:
                    $crate::algebra::ring::RingPolyEval<$nout>,
            )+
        {
            fn zeroize(&mut self) {
                $( for s in &mut self.$field { ::zeroize::Zeroize::zeroize(s); } )+
            }
        }

        impl<$modp: $modbound, const $lev: usize> ::core::ops::Drop for $ekey<$modp, $lev>
        where
            $(
                $ring<$nout, $modp, $crate::algebra::ring::form::Coefficient>:
                    $crate::algebra::ring::RingPolyEval<$nout>,
            )+
        {
            fn drop(&mut self) {
                ::zeroize::Zeroize::zeroize(self);
            }
        }

        impl<$modp: $modbound, const $lev: usize> ::zeroize::ZeroizeOnDrop for $ekey<$modp, $lev>
        where
            $(
                $ring<$nout, $modp, $crate::algebra::ring::form::Coefficient>:
                    $crate::algebra::ring::RingPolyEval<$nout>,
            )+
        {
        }

        impl<$modp: $modbound, const $lev: usize> ::core::fmt::Debug for $ekey<$modp, $lev>
        where
            $(
                $ring<$nout, $modp, $crate::algebra::ring::form::Coefficient>:
                    $crate::algebra::ring::RingPolyEval<$nout>,
            )+
        {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                f.debug_struct(stringify!($ekey))
                    .field("n", &$n)
                    .field("L", &$lev)
                    .finish_non_exhaustive()
            }
        }

        #[cfg(feature = "alloc")]
        #[allow(clippy::macro_metavars_in_unsafe)]
        impl<$modp: $modbound, const $lev: usize> $crate::conversion::CascadeKey
            for $key<$modp, $lev>
        where
            $(
                $ring<$nout, $modp, $crate::algebra::ring::form::Coefficient>:
                    $crate::algebra::ring::RingPolyEval<$nout>,
            )+
        {
            type Eval = $ekey<$modp, $lev>;
            fn to_eval_boxed(&self) -> ::alloc::boxed::Box<$ekey<$modp, $lev>> {
                let mut boxed = ::alloc::boxed::Box::<$ekey<$modp, $lev>>::new_uninit();
                let ptr = boxed.as_mut_ptr();
                // SAFETY: every `(mask, body)` slot of every RLev of every field is
                // written exactly once via `addr_of_mut!`, one **transformed sample
                // pair** at a time — peak stack stays one eval poly-pair (~64 KB at
                // n=2048), never a whole RLevEval (~1.15 MB) or the whole ~24.75 MB
                // key (which would overflow an 8 MB thread). Mirrors the coeff key's
                // `gen_conv_step_key_element_into` per-sample heap builder.
                unsafe {
                    $(
                        for i in 0..$rin {
                            for k in 0..$lev {
                                let sample = &self.$field[i].samples[k];
                                let pair = (
                                    <$ring<$nout, $modp, $crate::algebra::ring::form::Coefficient>
                                        as $crate::algebra::ring::RingPolyEval<$nout>>::to_eval(
                                        sample.mask,
                                    ),
                                    <$ring<$nout, $modp, $crate::algebra::ring::form::Coefficient>
                                        as $crate::algebra::ring::RingPolyEval<$nout>>::to_eval(
                                        sample.body,
                                    ),
                                );
                                ::core::ptr::addr_of_mut!((*ptr).$field[i].samples[k]).write(pair);
                            }
                        }
                    )+
                    boxed.assume_init()
                }
            }
        }

        #[doc = concat!(
            "Eval-key variant of [`", stringify!($cast), "`] (T7): the cascade key is ",
            "supplied **pre-transformed** ([`", stringify!($ekey), "`]), so each step's ",
            "`conv_step` runs without re-transforming the static step-key samples. ",
            "**Bit-identical** to [`", stringify!($cast), "`] (the NTT is exact)."
        )]
        pub fn $casteval<$modp: $modbound, const $lev: usize>(
            ct: &$crate::encryption::MLWECiphertext<
                $n, 1, $ring<1, $modp, $crate::algebra::ring::form::Coefficient>,
            >,
            key: &$ekey<$modp, $lev>,
            base: u64,
        ) -> $crate::encryption::RLWECiphertext<
            $n, $ring<$n, $modp, $crate::algebra::ring::form::Coefficient>,
        >
        where
            $(
                $ring<$nout, $modp, $crate::algebra::ring::form::Coefficient>:
                    $crate::algebra::ring::RingPolyEval<$nout>,
            )+
        {
            $crate::lwe_to_rlwe_cascade!(@chain_eval ($ring, $modp, $lev, base, key) ct ;
                $( ($field, $rin, $nin, $rout, $nout) )+)
        }
    };
}

// The macro expands the bare `$ring` ident (`Poly` / `PolyRns`) in this scope.
use crate::algebra::ring::element::Poly;
use crate::algebra::ring::rns_element::PolyRns;

// --- Toy single-prime instantiations -------------------------------------

lwe_to_rlwe_cascade! {
    n = 8,
    ring = Poly,
    mod_param = M,
    mod_bound = crate::algebra::zq::modulus::Modulus,
    levels = L,
    key = LweToRlweKeyN8,
    gen = gen_lwe_to_rlwe_key_n8,
    gen_boxed = gen_lwe_to_rlwe_key_n8_boxed,
    cast = lwe_to_rlwe_n8,
    eval_key = LweToRlweKeyN8Eval,
    cast_eval = lwe_to_rlwe_n8_eval,
    steps = [
        (keys_2, 8, 1, 4, 2),
        (keys_4, 4, 2, 2, 4),
        (keys_8, 2, 4, 1, 8),
    ],
}

lwe_to_rlwe_cascade! {
    n = 4,
    ring = Poly,
    mod_param = M,
    mod_bound = crate::algebra::zq::modulus::Modulus,
    levels = L,
    key = LweToRlweKeyN4,
    gen = gen_lwe_to_rlwe_key_n4,
    gen_boxed = gen_lwe_to_rlwe_key_n4_boxed,
    cast = lwe_to_rlwe_n4,
    eval_key = LweToRlweKeyN4Eval,
    cast_eval = lwe_to_rlwe_n4_eval,
    steps = [
        (keys_2, 4, 1, 2, 2),
        (keys_4, 2, 2, 1, 4),
    ],
}

// The VIA-C toy parameter set (`ViaCToyParams<64, 16, …>`) runs query
// compression at n₁ = 64 on the single-prime backend, so the toy end-to-end
// path uses this degree-64 cascade. Six steps (`log₂ 64`); the n₆₄ key is
// small (~150 KB at L = 12), so it stays by-value / no-alloc — unlike the
// degree-2048 paper instantiation, which needs the boxed builder.
lwe_to_rlwe_cascade! {
    n = 64,
    ring = Poly,
    mod_param = M,
    mod_bound = crate::algebra::zq::modulus::Modulus,
    levels = L,
    key = LweToRlweKeyN64,
    gen = gen_lwe_to_rlwe_key_n64,
    gen_boxed = gen_lwe_to_rlwe_key_n64_boxed,
    cast = lwe_to_rlwe_n64,
    eval_key = LweToRlweKeyN64Eval,
    cast_eval = lwe_to_rlwe_n64_eval,
    steps = [
        (keys_2, 64, 1, 32, 2),
        (keys_4, 32, 2, 16, 4),
        (keys_8, 16, 4, 8, 8),
        (keys_16, 8, 8, 4, 16),
        (keys_32, 4, 16, 2, 32),
        (keys_64, 2, 32, 1, 64),
    ],
}

// --- Toy RNS instantiation (paper query compression lives at q₁ RNS) ------

lwe_to_rlwe_cascade! {
    n = 8,
    ring = PolyRns,
    mod_param = B,
    mod_bound = crate::algebra::rns::basis::RnsBasis,
    levels = L,
    key = LweToRlweKeyRnsN8,
    gen = gen_lwe_to_rlwe_key_rns_n8,
    gen_boxed = gen_lwe_to_rlwe_key_rns_n8_boxed,
    cast = lwe_to_rlwe_rns_n8,
    eval_key = LweToRlweKeyRnsN8Eval,
    cast_eval = lwe_to_rlwe_rns_n8_eval,
    steps = [
        (keys_2, 8, 1, 4, 2),
        (keys_4, 4, 2, 2, 4),
        (keys_8, 2, 4, 1, 8),
    ],
}

// --- Paper-scale RNS instantiation (n₁ = 2048, depth 18) ------------------
//
// The VIA-C query-compression cascade key (`pp_qck`'s `ĉ_toRLWE` half). Its key
// is ~24.75 MB, so it can only be built on the heap — hence the whole
// instantiation is gated behind the `alloc` feature, and the heap builder
// `gen_lwe_to_rlwe_key_rns_n2048_boxed` is the supported constructor (the
// by-value `gen_…` would overflow any normal thread stack and is not
// re-exported). The cast `lwe_to_rlwe_rns_n2048` is consumed by the server.
#[cfg(feature = "alloc")]
lwe_to_rlwe_cascade! {
    n = 2048,
    ring = PolyRns,
    mod_param = B,
    mod_bound = crate::algebra::rns::basis::RnsBasis,
    levels = L,
    key = LweToRlweKeyRnsN2048,
    gen = gen_lwe_to_rlwe_key_rns_n2048,
    gen_boxed = gen_lwe_to_rlwe_key_rns_n2048_boxed,
    cast = lwe_to_rlwe_rns_n2048,
    eval_key = LweToRlweKeyRnsN2048Eval,
    cast_eval = lwe_to_rlwe_rns_n2048_eval,
    steps = [
        (keys_2, 2048, 1, 1024, 2),
        (keys_4, 1024, 2, 512, 4),
        (keys_8, 512, 4, 256, 8),
        (keys_16, 256, 8, 128, 16),
        (keys_32, 128, 16, 64, 32),
        (keys_64, 64, 32, 32, 64),
        (keys_128, 32, 64, 16, 128),
        (keys_256, 16, 128, 8, 256),
        (keys_512, 8, 256, 4, 512),
        (keys_1024, 4, 512, 2, 1024),
        (keys_2048, 2, 1024, 1, 2048),
    ],
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::algebra::ring::form::Coefficient;
    use crate::algebra::rns::basis::ConstRnsBasis;
    use crate::algebra::zq::modulus::ConstModulus;
    use crate::conversion::encrypt_lwe;
    use crate::encryption::types::SecretKey;
    use crate::sampling::distribution::Distribution;
    use crate::sampling::prg::Shake256Prg;

    const BASE: u64 = 8;
    const L: usize = 6;
    type R8 = Poly<8, ConstModulus<65537>, Coefficient>;
    type R4 = Poly<4, ConstModulus<65537>, Coefficient>;
    type P8 = Poly<8, ConstModulus<16>, Coefficient>;
    type P4 = Poly<4, ConstModulus<16>, Coefficient>;

    // n = 64 toy cascade. A ~2^34 modulus (the paper ViaCQ2 prime) gives ample
    // noise budget for the 6-step cascade (vs 3 steps at n8); base 8, depth 12
    // (8^12 = 2^36 ≥ 2^34 covers the modulus for gadget representability).
    type R64 = Poly<64, ConstModulus<17175674881>, Coefficient>;
    type P64 = Poly<64, ConstModulus<16>, Coefficient>;
    const BASE_64: u64 = 8;
    const L_64: usize = 12;

    #[test]
    fn cascade_key_count_n8() {
        let q = ConstModulus::<65537>;
        let mut prg = Shake256Prg::new(b"key-count-8");
        let sk = SecretKey::<8, R8>::keygen(q, Distribution::Ternary, &mut prg);
        let key = gen_lwe_to_rlwe_key_n8::<_, L>(&sk, BASE, Distribution::Ternary, &mut prg);
        // 8 + 4 + 2 = 14 = 2·(8−1).
        assert_eq!(key.keys_2.len() + key.keys_4.len() + key.keys_8.len(), 14);
        assert_eq!(key.keys_2.len(), 8);
        assert_eq!(key.keys_4.len(), 4);
        assert_eq!(key.keys_8.len(), 2);
    }

    #[test]
    fn cascade_key_count_n4() {
        let q = ConstModulus::<65537>;
        let mut prg = Shake256Prg::new(b"key-count-4");
        let sk = SecretKey::<4, R4>::keygen(q, Distribution::Ternary, &mut prg);
        let key = gen_lwe_to_rlwe_key_n4::<_, L>(&sk, BASE, Distribution::Ternary, &mut prg);
        // 4 + 2 = 6 = 2·(4−1).
        assert_eq!(key.keys_2.len() + key.keys_4.len(), 6);
    }

    #[test]
    fn cascade_full_roundtrip_n8() {
        let q = ConstModulus::<65537>;
        let p = ConstModulus::<16>;
        for message in 0..16u64 {
            let mut prg = Shake256Prg::new(b"cascade-roundtrip-8");
            let sk = SecretKey::<8, R8>::keygen(q, Distribution::Ternary, &mut prg);
            let lwe = encrypt_lwe(&sk, message, 16, Distribution::Ternary, &mut prg);
            let key = gen_lwe_to_rlwe_key_n8::<_, L>(&sk, BASE, Distribution::Ternary, &mut prg);
            let rlwe = lwe_to_rlwe_n8::<_, L>(&lwe, &key, BASE);
            // The cascade leaves the scalar at coefficient 0 of the degree-8 RLWE.
            let recovered: P8 = sk.decrypt(&rlwe, p);
            assert_eq!(recovered.coeff(0).to_u64(), message, "message {message}");
            for i in 1..8 {
                assert_eq!(
                    recovered.coeff(i).to_u64(),
                    0,
                    "message {message}, coeff {i}"
                );
            }
        }
    }

    #[test]
    fn cascade_full_roundtrip_n4() {
        let q = ConstModulus::<65537>;
        let p = ConstModulus::<16>;
        for message in 0..16u64 {
            let mut prg = Shake256Prg::new(b"cascade-roundtrip-4");
            let sk = SecretKey::<4, R4>::keygen(q, Distribution::Ternary, &mut prg);
            let lwe = encrypt_lwe(&sk, message, 16, Distribution::Ternary, &mut prg);
            let key = gen_lwe_to_rlwe_key_n4::<_, L>(&sk, BASE, Distribution::Ternary, &mut prg);
            let rlwe = lwe_to_rlwe_n4::<_, L>(&lwe, &key, BASE);
            let recovered: P4 = sk.decrypt(&rlwe, p);
            assert_eq!(recovered.coeff(0).to_u64(), message, "n4 message {message}");
        }
    }

    #[test]
    fn cascade_key_count_n64() {
        let q = ConstModulus::<17175674881>;
        let mut prg = Shake256Prg::new(b"key-count-64");
        let sk = SecretKey::<64, R64>::keygen(q, Distribution::Ternary, &mut prg);
        let key = gen_lwe_to_rlwe_key_n64::<_, L_64>(&sk, BASE_64, Distribution::Ternary, &mut prg);
        // 64 + 32 + 16 + 8 + 4 + 2 = 126 = 2·(64−1).
        assert_eq!(
            key.keys_2.len()
                + key.keys_4.len()
                + key.keys_8.len()
                + key.keys_16.len()
                + key.keys_32.len()
                + key.keys_64.len(),
            126,
        );
        assert_eq!(key.keys_2.len(), 64);
        assert_eq!(key.keys_64.len(), 2);
    }

    /// The degree-64 toy end-to-end cascade: every `p = 16` message round-trips
    /// to coefficient 0 with no noise leak (all other coefficients exactly 0).
    /// Key is generated once (degree-64 key is ~150 KB, by value / no-alloc).
    #[test]
    fn cascade_full_roundtrip_n64() {
        let q = ConstModulus::<17175674881>;
        let p = ConstModulus::<16>;
        let mut prg = Shake256Prg::new(b"cascade-roundtrip-64");
        let sk = SecretKey::<64, R64>::keygen(q, Distribution::Ternary, &mut prg);
        let key = gen_lwe_to_rlwe_key_n64::<_, L_64>(&sk, BASE_64, Distribution::Ternary, &mut prg);
        for message in 0..16u64 {
            let lwe = encrypt_lwe(&sk, message, 16, Distribution::Ternary, &mut prg);
            let rlwe = lwe_to_rlwe_n64::<_, L_64>(&lwe, &key, BASE_64);
            let recovered: P64 = sk.decrypt(&rlwe, p);
            assert_eq!(
                recovered.coeff(0).to_u64(),
                message,
                "n64 message {message}"
            );
            for i in 1..64 {
                assert_eq!(
                    recovered.coeff(i).to_u64(),
                    0,
                    "n64 msg {message} coeff {i}"
                );
            }
        }
    }

    #[test]
    fn cascade_determinism() {
        let q = ConstModulus::<65537>;
        let mk = || {
            let mut prg = Shake256Prg::new(b"cascade-det");
            let sk = SecretKey::<8, R8>::keygen(q, Distribution::Ternary, &mut prg);
            gen_lwe_to_rlwe_key_n8::<_, L>(&sk, BASE, Distribution::Ternary, &mut prg)
        };
        let a = mk();
        let b = mk();
        // Same seed ⇒ identical first step-key sample.
        for i in 0..2 {
            assert_eq!(
                a.keys_2[0].samples[0].mask.coeff(i).to_u64(),
                b.keys_2[0].samples[0].mask.coeff(i).to_u64(),
            );
        }
    }

    /// Paper-class: the full cascade on the RNS backend (query compression lives
    /// at the composite q₁). `Q = 7681·12289 ≈ 2^26.5`, enough budget for 3 steps.
    #[test]
    fn cascade_full_roundtrip_rns_n8() {
        type Rns8 = PolyRns<8, ConstRnsBasis<7681, 12289>, Coefficient>;
        let basis = ConstRnsBasis::<7681, 12289>;
        let p = ConstModulus::<16>;
        for message in [0u64, 1, 5, 11, 15] {
            let mut prg = Shake256Prg::new(b"cascade-rns-8");
            let sk = SecretKey::<8, Rns8>::keygen(basis, Distribution::Ternary, &mut prg);
            let lwe = encrypt_lwe(&sk, message, 16, Distribution::Ternary, &mut prg);
            let key =
                gen_lwe_to_rlwe_key_rns_n8::<_, L>(&sk, BASE, Distribution::Ternary, &mut prg);
            let rlwe = lwe_to_rlwe_rns_n8::<_, L>(&lwe, &key, BASE);
            let recovered: P8 = sk.decrypt(&rlwe, p);
            assert_eq!(
                recovered.coeff(0).to_u64(),
                message,
                "rns message {message}"
            );
        }
    }

    /// The field-by-field `…_boxed` builder draws PRG bytes in the same order as
    /// the by-value builder, so from the same `sk` + seed the two keys are
    /// functionally identical (verified here at the cheap n8 via equal cascade
    /// output). This is the correctness guard for the `unsafe` uninit writes.
    #[cfg(feature = "alloc")]
    #[test]
    fn boxed_gen_matches_by_value_n8() {
        let q = ConstModulus::<65537>;
        let mut prg = Shake256Prg::new(b"boxed-eq-sk");
        let sk = SecretKey::<8, R8>::keygen(q, Distribution::Ternary, &mut prg);

        let by_value = gen_lwe_to_rlwe_key_n8::<_, L>(
            &sk,
            BASE,
            Distribution::Ternary,
            &mut Shake256Prg::new(b"boxed-eq-keygen"),
        );
        let boxed = gen_lwe_to_rlwe_key_n8_boxed::<_, L>(
            &sk,
            BASE,
            Distribution::Ternary,
            &mut Shake256Prg::new(b"boxed-eq-keygen"),
        );

        // Both keys must drive the cascade to the same output for the same input.
        let lwe = encrypt_lwe(
            &sk,
            5,
            16,
            Distribution::Ternary,
            &mut Shake256Prg::new(b"boxed-eq-enc"),
        );
        let ra = lwe_to_rlwe_n8::<_, L>(&lwe, &by_value, BASE);
        let rb = lwe_to_rlwe_n8::<_, L>(&lwe, &boxed, BASE);
        for i in 0..8 {
            assert_eq!(
                ra.mask.coeff(i).to_u64(),
                rb.mask.coeff(i).to_u64(),
                "mask coeff {i}"
            );
            assert_eq!(
                ra.body.coeff(i).to_u64(),
                rb.body.coeff(i).to_u64(),
                "body coeff {i}"
            );
        }
    }

    /// Guards the paper-scale key layout (CCD Hotspot 2): 11 fields, each
    /// `RANK_IN · N_OUT = 2·n1 = 4096` RLev-bytes-worth at depth 18 over a
    /// 2-prime RNS. Each step key is `576 · 4096` bytes (`L·2limbs·2(mask+body)·8
    /// · (RANK_IN·N_OUT)`), so the whole key is `11 · 576 · 4096` =
    /// 25,952,256 B ≈ 24.75 MB. Instant (pure type layout); catches accidental
    /// field/degree/depth drift in the n2048 instantiation.
    #[cfg(feature = "alloc")]
    #[test]
    fn n2048_key_layout_is_24_75_mib() {
        use crate::algebra::rns::basis::paper::ViaCQ1Rns;
        let bytes = core::mem::size_of::<super::LweToRlweKeyRnsN2048<ViaCQ1Rns, 18>>();
        assert_eq!(
            bytes,
            11 * 576 * 4096,
            "n2048 key layout drifted from ~24.75 MB"
        );
    }
}

// ---------------------------------------------------------------------------
// Layer-6 SPIKE — depth-18 noise GO/NO-GO + boxed-builder peak-stack check.
//
// Validates depth-18 noise closure at the PAPER q₁ basis (`ViaCQ1Rns ≈ 2^75`,
// base 18) AND that the field-by-field `…_boxed` builder keeps peak stack small:
// each key is built with the heap builder on an 8 MB-stack thread — far below
// the whole-key size (~24.75 MB at n=2048 / ~5.3 MB at n=512), which a by-value
// build would require. `alloc`-gated (the boxed builders are); heavy (schoolbook
// O(n²)) so `#[ignore]`, release-only:
//   cargo test -p via-primitives --features alloc --release -- --ignored spike
// ---------------------------------------------------------------------------
#[cfg(all(test, feature = "alloc"))]
mod spike {
    // The macro emits a by-value generator for the n512 instantiation that this
    // module deliberately does not call (it uses only the boxed builder).
    #![allow(dead_code)]

    // `via-primitives` is `#![no_std]`; the test harness links `std`, but we name
    // it explicitly to reach `std::thread` for the bounded-stack spawn.
    extern crate std;

    use super::{gen_lwe_to_rlwe_key_rns_n2048_boxed, lwe_to_rlwe_rns_n2048};
    use crate::algebra::ring::element::Poly;
    use crate::algebra::ring::form::Coefficient;
    use crate::algebra::ring::rns_element::PolyRns;
    use crate::algebra::rns::basis::paper::ViaCQ1Rns;
    use crate::algebra::zq::modulus::ConstModulus;
    use crate::conversion::encrypt_lwe;
    use crate::encryption::types::SecretKey;
    use crate::sampling::distribution::Distribution;
    use crate::sampling::prg::Shake256Prg;

    // Intermediate-degree (n=512) instantiation — a cheap (~3 s) regression guard
    // for the cascade machinery at the paper basis/depth.
    crate::lwe_to_rlwe_cascade! {
        n = 512,
        ring = PolyRns,
        mod_param = B,
        mod_bound = crate::algebra::rns::basis::RnsBasis,
        levels = L,
        key = LweToRlweKeyRnsN512,
        gen = gen_lwe_to_rlwe_key_rns_n512,
        gen_boxed = gen_lwe_to_rlwe_key_rns_n512_boxed,
        cast = lwe_to_rlwe_rns_n512,
        eval_key = LweToRlweKeyRnsN512Eval,
        cast_eval = lwe_to_rlwe_rns_n512_eval,
        steps = [
            (keys_2, 512, 1, 256, 2),
            (keys_4, 256, 2, 128, 4),
            (keys_8, 128, 4, 64, 8),
            (keys_16, 64, 8, 32, 16),
            (keys_32, 32, 16, 16, 32),
            (keys_64, 16, 32, 8, 64),
            (keys_128, 8, 64, 4, 128),
            (keys_256, 4, 128, 2, 256),
            (keys_512, 2, 256, 1, 512),
        ],
    }

    const BASE: u64 = 18;
    const LV: usize = 18;
    const STACK: usize = 8 << 20; // 8 MB ≪ 24.75 MB whole key — boxing must hold.

    /// T7: the eval-key cascade `lwe_to_rlwe_n8_eval` (key pre-transformed via
    /// [`CascadeKey::to_eval_boxed`]) equals the coefficient-form `lwe_to_rlwe_n8`
    /// **exactly** — bit-identical, so storing the cascade key in eval form is a
    /// no-op on the result. NTT-friendly `q = 17` (≡ 1 mod 16) drives the real NTT
    /// at every step degree (2, 4, 8). Asserts ciphertext equality, not
    /// decrypt-correctness (`q` is too small to close noise — irrelevant here).
    #[test]
    fn lwe_to_rlwe_eval_matches_coeff_n8() {
        use super::{gen_lwe_to_rlwe_key_n8, lwe_to_rlwe_n8, lwe_to_rlwe_n8_eval};
        use crate::conversion::CascadeKey;
        type Q = Poly<8, ConstModulus<17>, Coefficient>;
        const L: usize = 4;
        let q = ConstModulus::<17>;
        let mut prg = Shake256Prg::new(b"cascade-eval-n8");
        let sk = SecretKey::<8, Q>::keygen(q, Distribution::Ternary, &mut prg);
        let key = gen_lwe_to_rlwe_key_n8::<_, L>(&sk, 2, Distribution::Ternary, &mut prg);
        let key_eval = key.to_eval_boxed();
        let lwe = encrypt_lwe(&sk, 5u64, 16, Distribution::Ternary, &mut prg);
        let coeff = lwe_to_rlwe_n8::<_, L>(&lwe, &key, 2);
        let eval = lwe_to_rlwe_n8_eval::<_, L>(&lwe, &key_eval, 2);
        assert_eq!(coeff.mask, eval.mask, "cascade eval mask mismatch");
        assert_eq!(coeff.body, eval.body, "cascade eval body mismatch");
    }

    /// Depth-18 noise closure at the paper q₁ basis, degree 512 (¼ paper degree).
    /// Builds the key with the **boxed** builder on an 8 MB thread, then
    /// round-trips all `p = 16` messages with exact-zero noise.
    #[test]
    #[ignore = "heavy depth-18 RNS cascade; run with --features alloc --release -- --ignored"]
    fn spike_n512_depth18_noise_closes() {
        type RnsQ1 = PolyRns<512, ViaCQ1Rns, Coefficient>;
        type P512 = Poly<512, ConstModulus<16>, Coefficient>;

        std::thread::Builder::new()
            .stack_size(STACK)
            .spawn(|| {
                let basis = ViaCQ1Rns::default();
                let p = ConstModulus::<16>;
                let mut prg = Shake256Prg::new(b"spike-n512-depth18");
                let sk = SecretKey::<512, RnsQ1>::keygen(basis, Distribution::Ternary, &mut prg);
                let key = gen_lwe_to_rlwe_key_rns_n512_boxed::<_, LV>(
                    &sk,
                    BASE,
                    Distribution::Ternary,
                    &mut prg,
                );
                for message in 0..16u64 {
                    let lwe = encrypt_lwe(&sk, message, 16, Distribution::Ternary, &mut prg);
                    let rlwe = lwe_to_rlwe_rns_n512::<_, LV>(&lwe, &key, BASE);
                    let recovered: P512 = sk.decrypt(&rlwe, p);
                    assert_eq!(recovered.coeff(0).to_u64(), message, "n512 msg {message}");
                    for i in 1..512 {
                        assert_eq!(
                            recovered.coeff(i).to_u64(),
                            0,
                            "n512 msg {message} coeff {i}"
                        );
                    }
                }
            })
            .expect("spawn spike thread")
            .join()
            .expect("spike panicked (noise did not close, or 8 MB stack overflowed?)");
    }

    /// **The depth-18 SPIKE (R1 GO/NO-GO).** Full paper degree n = 2048. Builds
    /// the ~24.75 MB key with the production **boxed** builder on an 8 MB thread
    /// (proving field-by-field boxing keeps peak stack ≪ the whole key), then
    /// round-trips all `p = 16` messages with exact-zero noise. PASS ⇒ paper path
    /// GO; panic ⇒ NO-GO (escalate to the L=20/B=16 param search).
    #[test]
    #[ignore = "very heavy depth-18 RNS cascade at n=2048; run with --features alloc --release -- --ignored"]
    fn spike_n2048_depth18_noise_closes() {
        type RnsQ1 = PolyRns<2048, ViaCQ1Rns, Coefficient>;
        type P2048 = Poly<2048, ConstModulus<16>, Coefficient>;

        std::thread::Builder::new()
            .stack_size(STACK)
            .spawn(|| {
                let basis = ViaCQ1Rns::default();
                let p = ConstModulus::<16>;
                let mut prg = Shake256Prg::new(b"spike-n2048-depth18");
                let sk = SecretKey::<2048, RnsQ1>::keygen(basis, Distribution::Ternary, &mut prg);
                let key = gen_lwe_to_rlwe_key_rns_n2048_boxed::<_, LV>(
                    &sk,
                    BASE,
                    Distribution::Ternary,
                    &mut prg,
                );
                for message in 0..16u64 {
                    let lwe = encrypt_lwe(&sk, message, 16, Distribution::Ternary, &mut prg);
                    let rlwe = lwe_to_rlwe_rns_n2048::<_, LV>(&lwe, &key, BASE);
                    let recovered: P2048 = sk.decrypt(&rlwe, p);
                    assert_eq!(recovered.coeff(0).to_u64(), message, "n2048 msg {message}");
                    for i in 1..2048 {
                        assert_eq!(
                            recovered.coeff(i).to_u64(),
                            0,
                            "n2048 msg {message} coeff {i}"
                        );
                    }
                }
            })
            .expect("spawn spike thread")
            .join()
            .expect("spike panicked (depth-18 noise did NOT close, or 8 MB stack overflowed)");
    }
}
